<font size=6 color='darkblue'><b>Curso em Vídeo - Curso de Python 3.0</b></font>
<p>Jupyter Notebook criado por Bruno C. Nogueira.</p>

<p>Este notebook foi criado com o objetivo de reunir as soluções dos exercícios propostos durante o curso <b>Curso de Python 3.0</b> do professor <b>Gustavo Guanabara</b>, oferecido pelo portal <a href="http://www.cursoemvideo.com">Curso em Vídeo</a> e o <a href="https://www.youtube.com/c/CursoemV%C3%ADdeo">Canal Curso em Vídeo</a>. Todos os créditos das soluções apresentadas são do próprio professor.</p>

<p>A intenção é fornecer um acesso centralizado às respostas para ajudar os novos estudantes que desejam conferir suas soluções após tentarem resolver os desafios por conta própria. É importante reforçar que consultar as soluções deve ser a última etapa no processo de aprendizado.</p>

<p>O uso de Jupyter Notebooks em conjunto com o <a href="https://www.anaconda.com/">Anaconda</a> é uma abordagem recomendada para experimentação interativa, mas não substitui outras ferramentas, como o PyCharm, durante a prática de programação. Além disso, é necessário ter cuidado com a execução de comandos em notebooks, uma vez que podem ter comportamentos distintos em relação a outras IDEs.</p>

<p>Muitas das tags HTML usadas na criação deste material foram baseadas no conhecimento adquirido através do <a href="https://www.youtube.com/playlist?list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o">Curso de HTML 5</a> do Curso em Vídeo.</p>

<font color='red'><b>Atenção: Tente resolver os desafios antes de consultar as respostas, para maximizar seu aprendizado!</b></font>

# <font color = 'green'><a name="Mundo1">Mundo 1</font>

##  <font color = 'red'> Desafio 001 - Deixando tudo pronto</font>
Crie um script python que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas de acordo com o valor digitado.
<p> Exemplo da mensagem: "Olá Bruno! Prazer em te conhecer! </P>

In [2]:
nome = input('Qual o seu nome?')
print('Olá',nome,"!","Prazer em te conhecer!")

Qual o seu nome?Bruno
Olá Bruno ! Prazer em te conhecer!


##  <font color = 'red'> Desafio 002 - Respondendo ao Usuário</font>
Crie um script python que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a fata formatada.
<p> Exemplo da mensagem: "Você nasceu no dia 17 de Março de 1978. </p>

In [7]:
dia = input('Qual seu dia de nascimento? ')
mes = input('Qual seu mês de nascimento? ')
ano = input('Qual seu ano de nascimento? ')
print('Você nasceu no dia',dia,'de',mes,'de',ano,".")

Qual seu dia de nascimento? 27
Qual seu mês de nascimento? dezembro
Qual seu ano de nascimento? 1985
Você nasceu no dia 27 de dezembro de 1985 .


##  <font color = 'red'> Desafio 003 - Somando dois números</font>
Crie um script python que leia dois números e **tente** mostrar a soma entre eles. <p>Observação: Provavelmente você não conseguirá resolver esse desafio sem fazer uma pesquisa. Mas não se preocupe, será explicado na próxima aula.
<p> Exemplo de saída: "A soma é 10" <p>

In [11]:
n1 = input('Digite um número:')
n2 = input('Digite outro número:')
s = n1 + n2
print('A soma é', s)

Digite um número:4
Digite outro número:6
A soma é 46


##  <font color = 'red'> Desafio 004 - Dissecando uma Variável</font>
Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo respondendo as sequintes perguntas:
<br>O tipo primitivo é: <br>Só tem espaços? <br>É um número?
<br>É alfabético? <br>É alfanumérico? <br>Está em maiúscula?
<br>Está em minúscula? <br>Está capitularizada?

In [30]:
a = input('Digite algo: ')
print('O tipo primitivo é {}:'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúscula? {}'.format(a.isupper()))
print('Está em minúscula? {}'.format(a.islower()))
print('Está capitularizada? {}'.format(a.istitle()))

Digite algo: Python
O tipo primitivo é <class 'str'>:
Só tem espaços? False
É um número? False
É alfabético? True
É alfanumérico? True
Está em maiúscula? False
Está em minúscula? False
Está capitularizada? True


##  <font color = 'red'> Desafio 005 - Antecessor e Sucessor </font>
Faça um programa que leia um número inteiro e mostra na tela seu sucessor e seu antecessor.

In [34]:
n = int(input('Digite um número: '))
print('Antes do número {} vem o número {} e depois número {}'.format(n, n-1, n+2 ))

Digite um número: 10
Antes do número 10 vem o número 9 e depois número 12


##  <font color = 'red'> Desafio 006 - Dobro, Triplo, Raiz Quadrada </font>
Crie um algoritmo que leia um número e mostre o seu dobro, tripo e raiz quadrada.

In [39]:
n = int(input('Digite um número: '))
print('O dobro de {} é {}, tripo é {} e a raiz quadrada é {:.0f}.'.format(n, n*2, n*3, n**(1/2)))

Digite um número: 9
O dobro de 9 é 18, tripo é 27 e a raiz quadrada é 3.


##  <font color = 'red'> Desafio 007 - Média Aritmética</font>
Desenvolda um programa que leia as duas notas de um aluno, calcule e mostre sua média.

In [45]:
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
media = (nota1 + nota2) / 2
print('A média da primeira nota, {} com a segunda nota, {} é {} '.format(nota1, nota2, (media)))

Digite a primeira nota: 5
Digite a segunda nota: 10
A média da primeira nota, 5.0 com a segunda nota, 10.0 é 7.5 


##  <font color = 'red'> Desafio 008 - Conversor de Medidas </font>
Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.

In [46]:
metros = float(input('Digite o valor em metros a ser convertido: '))
cent = metros * 100
mili = metros * 1000
print('{} m é igual a {}cm ou {}mm'.format(metros, cent, mili))

Digite o valor em metros a ser convertido: 1
1.0 m é igual a 100.0cm ou 1000.0mm


##  <font color = 'red'> Desafio 009 - Tabuada </font>
Faça um programa que leia um número inteiro qualquer e mostra na tela a sua tabuada. (Tente fazer o mais bonito possível).

In [57]:
n = int(input('Qual a tabuada de: '))
print(' ')
n1 =  n * 1
n2 =  n * 2
n3 =  n * 3
n4 =  n * 4
n5 =  n * 5
n6 =  n * 6
n7 =  n * 7
n8 =  n * 8
n9 =  n * 9
n10 = n * 10
print('Tabuada de {}'.format(n))
print('{:>2} x {:<2} = {:<2}'.format(n, 1, n1))
print('{:>2} x {:<2} = {:<2}'.format(n, 2, n2))
print('{:>2} x {:<2} = {:<2}'.format(n, 3, n3))
print('{:>2} x {:<2} = {:<2}'.format(n, 4, n4))
print('{:>2} x {:<2} = {:<2}'.format(n, 5, n5))
print('{:>2} x {:<2} = {:<2}'.format(n, 6, n6))
print('{:>2} x {:<2} = {:<2}'.format(n, 7, n7))
print('{:>2} x {:<2} = {:<2}'.format(n, 8, n8))
print('{:>2} x {:<2} = {:<2}'.format(n, 9, n9))
print('{:>2} x {:>2} = {:<2}'.format(n, 10, n10))


Qual a tabuada de: 5
 
Tabuada de 5
 5 x 1  = 5 
 5 x 2  = 10
 5 x 3  = 15
 5 x 4  = 20
 5 x 5  = 25
 5 x 6  = 30
 5 x 7  = 35
 5 x 8  = 40
 5 x 9  = 45
 5 x 10 = 50


##  <font color = 'red'> Desafio 010 - Conversor de Moedas</font>
Crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar. <br> Considere UDS 1 = R$ 3,27

In [64]:
real = float(input('Digite quantos reais você tem: '))
dolar = real / 3.27
print('Com {} reais você pode comprar {} dolares.'.format(real, dolar))

Digite quantos reais você tem: 6.54
Com 6.54 reais você pode comprar 2.0 dolares.


##  <font color = 'red'> Desafio 011 - Pintando Parede </font>
Faça um programa que leia a largura e a altura de uma parede em metros, calcule a sua área e a quantidade de tinta necessária para pintá-la, sabendo que cada litro de tinta, pinta uma área de 2m².

In [69]:
lar = float(input('Digite a largura da parede em metros: '))
alt = float(input('Digite a altura da parede em metros: '))
area = lar * alt
tinta = (area / 2)
print('Uma parede de {}m de largura por {}m de altura tem uma área de {}m².'.format(lar, alt, area))
print('Logo será necessário {} litros de tinta para pinta-la.'.format(tinta))

Digite a largura da parede em metros: 1
Digite a altura da parede em metros: 3
Uma parede de 1.0m de largura por 3.0m de altura tem uma área de 3.0m².
Logo será necessário 1.5 litros de tinta para pinta-la.


##  <font color = 'red'> Desafio 012 - Calculando Descontos</font>
Faça um algoritmo que leia o preço de um produto e mostre seu novo preço, com 5% de desconto.

In [71]:
p = float(input('Digite o preço do produto: '))
desc = p - (p * 0.05)
print('O valor do produto com 5% de desconto é {}'.format(desc))

Digite o preço do produto: 50
O valor do produto com 5% de desconto é 47.5


##  <font color = 'red'> Desafio 013 - Reajuste Salarial </font>
Faça um algorítmo que leia o salário de um funcionário e mostre seu novo salário, com 15% de aumento.

In [5]:
s = float(input('Digite o seu salário: '))
a = s + (s * 0.15)
print('Seu novo salário é {}'.format(a))

Digite o seu salário: 50
Seu novo salário é 57.5


##  <font color = 'red'> Desafio 014 - Conversor de Temperaturas </font>
Escreva um programa que converta uma temperatura digitada em °C em °F.

In [3]:
c = float(input('Informe a temperatura em °C: '))
f = ((9 * c) / 5) + 32
#se quiser utilizar a ordem de precedência não precisa coloar os ()
#logo a variável f pode ficar: f = 9 * c / 5 + 32
print('A temperatura de {} °C corresponde a {} em °F.'.format(c, f))

Informe a temperatura em °C: 45
A temperatura de 45.0 °C corresponde a 113.0 em °F.


##  <font color = 'red'> Desafio 015 - Aluguel de Carro</font>
Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado e a quantidade de dias pelos quais ele foi alugado. Calcule o preço a pagar, sabendo que o carro custa 60,00 reais por dia e 0,15 centavos por Km rodado.

In [11]:
km = float(input('Quantos km o carro percorreu? '))
dias = int(input('Por quantos dias o carro foi alugado? '))
pr = (km * 0.15) + (dias * 60)
print('O carro percorreu {} por {} dias. O valor do aluguel é R${:.2f}'.format(km, dias, pr))

Quantos km o carro percorreu? 350
Por quantos dias o carro foi alugado? 3
O carro percorreu 350.0 por 3 dias. O valor do aluguel é R$232.50


##  <font color = 'red'> Desafio 016 - Quebrando um número</font>
Crie um programa que leia um número Real qualquer pelo teclado e mostre na tela a sua porção inteira.</br>
Ex.: Digite um número: 6.127. O número 6.127 tem a parte inteira 6.

In [23]:
#sem importar uma biblioteca
n = float(input('Digite um valor: '))
inteiro = n // 1
print('O número {} tem a parte inteira {}.'.format(n, inteiro))

Digite um valor: 34.421
O número 34.421 tem a parte inteira 34.0.


In [20]:
#sem importar uma biblioteca e usando a função int
n = float(input('Digite um valor: '))
print('O número {} tem a parte inteira {}.'.format(n, int(n)))

Digite um valor: 6.127
O número 6.127 tem a parte inteira 6.


In [17]:
#importando toda biblioteca
import math
n = float(input('Digite um valor: '))
print('O número {} tem a parte inteira {:.1f}.'.format(n, math.trunc(n)))

Digite um valor: 6.127
O número 6.127 tem a parte inteira 6.0.


In [19]:
#importando só a função trunc
from math import trunc
n = float(input('Digite um valor: '))
print('O número {} tem a parte inteira {:.1f}.'.format(n, trunc(n)))

Digite um valor: 6.127
O número 6.127 tem a parte inteira 6.0.


##  <font color = 'red'> Desafio 017 - Catetos e Hipotenusa</font>
Faça um programa que leia o comprimento do cateto oposto e do cateto adjacente de um triângulo retângulo, calcula e mostre o comprimento da hipotenusa.

In [30]:
#o quadrado da hipotenusa é igual à soma dos quadrados dos catetos.
#Sem importar uma biblioteca
copt = float(input('Digite o valor do cateto oposto: '))
cadj = float(input('Digite o valor do cateto adjacente: '))
hipo = ((copt**2) + (cadj**2)) ** (1/2)
print('O valor da hipotenusa vale: {:.2f} '.format(hipo))

Digite o valor do cateto oposto: 3
Digite o valor do cateto adjacente: 4
O valor da hipotenusa vale: 5.0 


In [32]:
#Importando somente a função hypot da biblioteca math
from math import hypot
copt = float(input('Digite o valor do cateto oposto: '))
cadj = float(input('Digite o valor do cateto adjacente: '))
hipo = hypot(copt, cadj)
print('O valor da hipotenusa vale: {:.2f} '.format(hipo))

Digite o valor do cateto oposto: 3
Digite o valor do cateto adjacente: 4
O valor da hipotenusa vale: 5.00 


##  <font color = 'red'> Desafio 018 - Seno, Cosseno e Tangente</font>
Faça um programa que leia um ângulo qualquer e mostre na tela o valor do seno, cosseno e tangente desse ângulo.

In [35]:
#Importanto somente as funções sin, cos e tan da biblioteca math
from math import sin, cos, tan, radians
ang = float(input('Digite o valor do ângulo: '))
seno = sin(radians(ang))
cosseno = cos(radians(ang))
tangente = tan(radians(ang))
print('O âgulo de {} tem o seno de {:.2f}, cosseno de {:.2f} e tangente de {:.2f}'.format(ang, seno, cosseno, tangente))

Digite o valor do ângulo: 30
O âgulo de 30.0 tem o seno de 0.50, cosseno de 0.87 e tangente de 0.58


##  <font color = 'red'> Desafio 019 - Sorteando um item na lista</font>
Um professor quer sortear um dos seus quatro alunos para apagar o quadro. Faça um programa que ajude ele, lendo o nome deles e escrevendo o nome do escolhido.

In [39]:
#Importar somente a função choice da biblioteca random
#Não é necessário declarar que é uma string, mas será usado.
from random import choice
a1 = str(input('Primeiro aluno: '))
a2 = str(input('Segundo aluno: '))
a3 = str(input('Terceiro aluno: '))
a4 = str(input('Quarto aluno: '))
#lista em python fica entre []
lista = [a1, a2, a3, a4]
aluno = choice(lista)
print('O aluno escolhido foi {}'.format(aluno))

Primeiro aluno: A
Segundo aluno: B
Terceiro aluno: C
Quarto aluno: D
O aluno escolhido foi B


##  <font color = 'red'> Desafio 020 Sorteando uma ordem na lista</font>
O mesmo professor do desafio anterior quer sortear a ordem de apresentaão de trabalhos dos alunos. Faça um programa que leia o nome dos quatro alunos e mostre a ordem sorteada.

In [46]:
from random import shuffle
a1 = str(input('Primeiro aluno: '))
a2 = str(input('Segundo aluno: '))
a3 = str(input('Terceiro aluno: '))
a4 = str(input('Quarto aluno: '))
lista = [a1, a2, a3, a4]
shuffle(lista)
print('A ordem de apresentação sera: ')
print(lista)

Primeiro aluno: A
Segundo aluno: B
Terceiro aluno: C
Quarto aluno: D
A ordem de apresentação sera: 
['C', 'B', 'D', 'A']


##  <font color = 'red'> Desafio 021 Tocando um MP3</font>
Faça um programa em Python que abra e reproduza o áudio de um arquivo MP3.

In [51]:
 !pip3 install pygame

In [2]:
import pygame
pygame.init()
pygame.mixer.music.load(r'C:\Users\Bruno\Downloads\alok.mp3')
pygame.mixer.music.play()
#pygame.event.wait(): para parar a música quando ela terminar
pygame.event.wait()

<Event(4352-AudioDeviceAdded {'which': 1, 'iscapture': 0})>

In [3]:
#para interromper a música
pygame.mixer.music.stop()

##  <font color = 'red'> Desafio 022 - Analisador de Textos</font>
Crie um programa que leia o nome completo de uma pessoa e mostre:
<br> O nome com todas as letras maiúsculas; </br>
<br> O nome com todas as letras minúsculas; </br>
<br> Quantas letras ao todo (sem considerar espaços); e </br>
<br> Quantas letras tem o primeiro nome. </br>

In [16]:
nome = input('Digite seu nome completo: ')
print(nome.upper())
print(nome.lower())
nnome = nome.replace(' ', '')
n1nome = nome.split()

print('O nome {} possui {} letras.'.format(nome.strip(), len(nnome)))
print('O primeiro nome possui {} letras.'.format(len(n1nome[0])))

Digite seu nome completo:  Bruno 
 BRUNO 
 bruno 
O nome Bruno possui 5 letras.
O primeiro nome possui 5 letras.


##  <font color = 'red'> Desafio 023 - Separando dígitos de um número </font>
Faça um programa que leia um número de 0 a 9999 e mostra na tela cada um dos digitos separados. </br>
- Ex.: Digite um número: 1834
 - unidade: 4
 - dezena: 3
 - centena 8
 - milhar: 1

In [1]:
#resolvendo por meio de string. 
#Contudo essa forma gera um erro se não for usado os 4 dígitos. Teste e confira.
num = int(input('Informe um número: '))
n = str(num)
print(f'Analisando o número {num}.')
print(f'Unidade: {n[3]}.')
print(f'Dezenna: {n[2]}.')
print(f'Centena: {n[1]}.')
print(f'Milhar {n[0]}.')

Informe um número: 1234
Analisando o número 1234.
Unidade: 4.
Dezenna: 3.
Centena: 2.
Milhar 1.


In [46]:
#resolvendo de forma matemática
num = int(input('Informe um número: '))
u = (num // 1) % 10
d = (num // 10) % 10
c = (num // 100) % 10
m = (num // 1000) % 10
print(f'Analisando o número {num}')
print(f'Unidade: {u}')
print(f'Dezena: {d}')
print(f'Centena: {c}')
print(f'Milhar {m}')

Informe um número: 234467
Analisando o número 234467
Unidade: 7
Dezena: 6
Centena: 4
Milhar 4


## <font color = 'red'> Desafio 024 - Verificando as primeiras letras de um texto </font>
Crie um programa que leia o nome de uma cidade e diga se ela começa ou não com o nome "SANTO".

In [8]:
cid = str(input('Digite o nome de uma cidade:')).strip()
#strip() retira os espaços
print(cid[:5].upper() == 'SANTO')
#upper() altera a string para maiúsculo.
#poderia altarar a string para lower()

Digite o nome de uma cidade:kjfa sdflja sdflja sljfa sjfd
False


##  <font color = 'red'> Desafio 025 -  Procurando uma string dentro de outra </font>
Crie um programa que leia o nome de uma pessoa e diga se ala tem "SILVA" no nome.

In [39]:
nome = str(input('Digite seu nome: ' )).strip().upper()
#ou nome = str(input('Digite seu nome: ' )).strip()
print(f'O nome que você digitou foi: {nome}.')
print(f'Existe Silva nesse nome?: {"SILVA" in nome}')
#ou print(f'Existe Silva nesse nome?: {"SILVA" in nome.upper()}')
#poderia altarar a string para lower()

Digite seu nome:    Silva
O nome que você digitou foi: SILVA.
Existe Silva nesse nome?: True


##  <font color = 'red'> Desafio 026 - Primeira e última ocorrência de uma string </font>
Faça um programa que leia uma frase pelo teclado e mostre:
<br>Quantas vezes aparece a letra "A"</br>
<br>Em que posição ela aparece a primeira vez</br>
<br>Em que posição ela aparece a última vez</br>

In [66]:
frase = str(input('Digite uma frase: ')).upper().strip()
#a = frase.count('A')
print(f'A letra A aparece {frase.count("A")} vezes.')
print(f'A letra A aparece pela primeira vez na posição {frase.find("A")+1}.')
print(f'A letra A aparece pela última vez na posição {frase.rfind("A")+1}.')

Digite uma frase: Arara Azul
A letra A aparece 4 vezes.
A letra A aparece pela primeira vez na posição 1.
A letra A aparece pela última vez na posição 7.


##  <font color = 'red'> Desafio 027 - Primeiro e último nome de uma pessoa </font>
Faça um programa que leia o nome completo de uma pessoa, mostrando em seguida o primeiro e o último nome separadamente.</p>
Ex.: Ana Maria de Souza
<br>Primeiro: Ana</br>
<br>Último: Souza</br>

In [77]:
nome = str(input('Digite seu nome compleo: ')).strip().split()
print(f'Primeiro nome: {nome[0]}')
print(f'Último nome: {nome[-1]}')

Digite seu nome compleo: Bruno C Nogueira
Primeiro nome: Bruno
Último nome: Nogueira


##  <font color = 'red'> Desafio 028 - Jogo da Adivinhação </font>
Escreva um programa que faça o computador "pensar' em um número inteiro entre 0 e 5 e peça para o usuário tentar descobrir qual foi o número escolhido pelo computador. </P>
O programa deverá escrever na tela se o usuário venceu ou perdeu.

In [104]:
#import random, time
from random import randint
from time import sleep

print('-=-'*30)
print('Vou pensar em um número entre 0 e 5. Tente adivinhar...')
print('-=-'*30)

computador = random.randint(0, 5)
jogador = int(input('Em que número eu pensei? '))
print('PROCESSANDO...')
sleep(2)
if jogador == computador:
    print(f'PARABÉNS! Você conseguiu me vencer!')
else:
    print(f'GANHEI! Eu pensei no número {computador} e não no número {jogador}!')


-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Vou pensar em um número entre 0 e 5. Tente adivinhar...
-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Em que número eu pensei? 4
PROCESSANDO...
GANHEI! Eu pensei no número 0 e não no número 4!


##  <font color = 'red'> Desafio 029 - Radar eletrônico</font>
Escreva um programa que leia a velocidade de um carro. </p>
Se ele ultrapassar 80km/h, mostre uma mensagem dizendo que ele foi multado.</p>
A multa vai custar R$ 7,00 por cada km acima do limite.

In [3]:
veloc = float(input('Qual é a velocidade do carro? '))
multa = (veloc - 80) * 7
if veloc > 80:
            print('Atenção. O limite de velocidade é 80km/h.')
            print(f'Você estava dirigindo a {veloc:.0f}km/h')
            print(f'Vovê foi multado em R${multa:.2f}.')
else:
    print('Você está dentro do limite de velocidade. Parabéns!')

Qual é a velocidade do carro? 


ValueError: could not convert string to float: ''

##  <font color = 'red'> Desafio 030 - Par ou ímpar </font>
Crie um programa que leia um número inteiro e mostre na tela se ele é PAR ou ÍMPAR.

In [3]:
n = int(input('Digite um número: '))
#O resto da divisão por 2 tem que ser zero par ser par e 1 para ser ímpar.
if n % 2 == 0: 
    print(f'O número {n} é par!')
else:
    print(f'O número {n} é impar!')

Digite um número: 5788
O número 5788 é par!


##  <font color = 'red'> Desafio 031 - Custo da Viagem </font>
Desenvolva um programa que pergunte a distância de uma viagem em Km. </p>
Calcule o preço da passagem, cobrando 0,50 centavos por Km para viagens de até 200km e 0,45 centavos para viagens mais longas.

In [18]:
dist = float(input('Qual a distância da sua viagem: '))
if dist <= 200:
    passagem = dist * 0.50
else:
    passagem = dist * 0.45
    
#passagem = dist * 0.50 if dist <= 200 else dist * 0.45
print(f'O preço da passagem para {dist:.0f}km é R${passagem:.2f}')

Qual a distância da sua viagem: 500
O preço da passagem para 500km é R$225.00


##  <font color = 'red'> Desafio 032 - Ano Bissexto </font>
Faça um programa que leia um ano qualquer e mostre se ele é BISSEXTO.

In [28]:
from datetime import date

ano = int(input('Digite o ano para verificar se é Bissexto. Para o ano atual selecione 0. '))
if ano == 0:
    ano = date.today().year
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
    print(f'O ano {ano} é Bissexto.')
else:
    print(f'O ano {ano} não é Bissexto.')

Digite o ano para verificar se é Bissexto. Para o ano atual selecione 0. 0
O ano 2022 não é Bissexto.


##  <font color = 'red'> Desafio 033 - Maior e menor valores </font>
Faça um programa que leia três números e mostre qual é o maior e qual é o menor.

In [29]:
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))

if n1 > n2 and n1 > n3:
    maior = n1
if n2 > n1 and n2 > n3:
    maior = n2
if n3 > n1 and n3 > n2:
    maior = n3
if n1 < n2 and n1 < n3:
    menor = n1
if n2 < n1 and n2 < n3:
    menor = n2
if n3 < n1 and n3 < n2:
    menor = n3
    
print(f'O maior número é {maior}.')
print(f'O menor número é {menor}.')

Digite o primeiro número: 30
Digite o segundo número: 10
Digite o terceiro número: 20
O maior número é 30.
O menor número é 10.


In [32]:
#outra forma de resolver o exercício acima
n4 = int(input('Digite o primeiro número: '))
n5 = int(input('Digite o segundo número: '))
n6 = int(input('Digite o terceiro número: '))

maior = n4
if n5 > n4 and n5 > n6:
    maior = n5
if n6 > n4 and n6 > n5:
    maior = n6
    
menor = n4
if n5 < n4 and n5 < n6:
    menor = n5
if n6 < n4 and n6 < n5:
    menor = n6

print(f'O maior número é {maior}.')
print(f'O menor número é {menor}.')

Digite o primeiro número: 5
Digite o segundo número: 6
Digite o terceiro número: 7
O maior número é 7.
O menor número é 5.


##  <font color = 'red'> Desafio 034 - Aumentos múltiplos </font>
Escreva um programa que pergunte o salário de um funcionário e calcule o valor do seu aumento.</P>
Para salários superiores a R$ 1.250,00, calcule um aumento de 10%.
Para os inferiores ou iguais, o aumento é de 15%.

In [42]:
salario = float(input('Informe o seu salário: '))

if salario > 1250:
    promo = str('10%')
    aumento = salario * 0.10
    novo = salario + aumento
else:
    promo = str('15%')
    aumento = salario * 0.15
    novo = salario + aumento

print(f'Seu salário é de R${salario:.2f}. Você recebeu um aumento de {promo}.')
print(f'Seu novo salário é de R${novo:.2f}')

Informe o seu salário: 5000
Seu salário é de R$5000.00. Você recebeu um aumento de 10%.
Seu novo salário é de R$5500.00


##  <font color = 'red'> Desafio 035 -  Analisando Triângulo v1.0 </font>
Desenvolva um programa que leia o comprimeiro de três retas e diga ao usuário se elas podem ou não formar um triângulo.

In [44]:
r1 = float(input('Digite a primeira reta: '))
r2 = float(input('Digite a segunda reta: '))
r3 = float(input('Digite a terceira reta: '))

if r1 < r2 + r3 and r2 < r1 + r3 and r3 < r1 + r2:
    print(f'Com as retas {r1}, {r2} e {r3} é possível formar um triâgulo.')
else:
    print(f'Com as retas {r1}, {r2} e {r3} não é possível formar um triâgulo.')
          

Digite a primeira reta: 2
Digite a segunda reta: 4
Digite a terceira reta: 6
Com as retas 2.0, 4.0 e 6.0 não é possível formar um triâgulo.


# <font color = 'green'><a name="Mundo2">Mundo 2</font>

##  <font color = 'red'> Desafio 036 - Aprovando Empréstimo</font>
Escreva um programa para aprovar o emprétimo bancário para a compra de uma casa. 
O programa vai perguntar o valor da casa, o salário do comprador e em quantos anos ele vai pagar.
Calcule o valor da prestação mensal, sabendo que ela não pode exceder 30% do salário ou o empréstimo será negado

In [2]:
vcasa = float(input('Digite o valor da casa: '))
salario = float(input('Digite o salário do comprador: '))
anos = int(input('Digite os anos de financiamento:  '))
parcela = (vcasa / (anos * 12))
teto = salario * 0.3

if parcela <= teto:
    print('Parabéns seu empréstimo foi Aprovado!')
    print(f'Uma casa de R${vcasa:.2f} em 7 anos terá uma prestação de {parcela:.2f} mensais.')
else:
    print('Empréstimo Negado!')
    print(f'Uma casa de R${vcasa:.2f} em 7 anos terá uma prestação de {parcela:.2f} mensais.')


Digite o valor da casa: 80000
Digite o salário do comprador: 1600
Digite os anos de financiamento:  7
Empréstimo Negado!
Uma casa de R$80000.00 em 7 anos terá uma prestação de 952.38 mensais.


##  <font color = 'red'> Desafio 037 - Conversor de Bases Numéricas</font>
Escreva um programa que leia um número inteiro qualquer e peça para o usuário escolher qual será a base de conversão:
- 1 para binário
- 2 para octal
- 3 para hexadecimal

In [15]:
n = int(input('Digite um número inteiro: '))

print('''Deseja converter para qual base:
[ 1 ] Converter para binário.
[ 2 ] Converter para binário.
[ 3 ] Converter para binário.''')
base = int(input('Digite sua opção: '))

if base == 1:
    print(f'{n} convertido para Binário é igual a {bin(n)[2:]}.')
elif base == 2:
    print(f'{n} convertido para Octal é igual a {oct(n)[2:]}.')
elif base == 3:
    print(f'{n} convertido para Hexadecimal é igual a {hex(n)[2:]}.')
else:
    print('Opção inválida. Tente novamente.')

Digite um número inteiro: 444
Deseja converter para qual base:
[ 1 ] Converter para binário.
[ 2 ] Converter para binário.
[ 3 ] Converter para binário.
Digite sua opção: 5
Opção inválida. Tente novamente.


##  <font color = 'red'> Desafio 038 - Comparando números</font>
Escreva um programa que leia dois números inteiros e compare-os, motrando na tela uma mensagem:
- O primeiro valor é maior.
- O segundo valor é maior.
- Não existe valor maior, os dois são iguais.

In [18]:
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

if n1 > n2:
    print('O primeiro número é maior.')
elif n2 > n1:
    print('O segundo número é maior.')
else:
    print('Os dois números são iguais.')

Digite o primeiro número: 5
Digite o segundo número: 5
Os dois valores são iguais.


##  <font color = 'red'> Desafio 039 - Alistamento Militar</font>
Faça um programa que leia o ano de nascimento de um jovem e informe, de  acordo com sua idade:
- Se ele ainda vai se alistar no serviço militar.
- Se é a hora de se alistar.
- Se já passou do tempo do alistamento.

Seu programa também deverá mostrar o tempo que falta ou que passou do prazo.

In [36]:
from datetime import date

nasc = int(input('Ano de nascimento: '))
ano = date.today().year
idade = ano - nasc
alistamento = 18 - idade
if nasc <= ano:
    if idade < 18:
        print(f'Você nasceu em {nasc}, tem {idade} anos de idade em {ano}.')
        print(f'Ainda faltam {alistamento} para seu alistamento.')
        print(f'Você deve se alistar em {ano + alistamento}')
    elif idade == 18:
        print(f'Você nasceu em {nasc}, tem {idade} anos de idade em {ano}.')
        print(f'Você deve se alistar esse ano.')
    elif idade > 18:
        print(f'Você nasceu em {nasc}, tem {idade} anos de idade em {ano}.')
        print(f'Já passaram {(alistamento) * -1} anos da data de alistamento.')
        print(f'Procure a junta militar.')
else:
    print(f'Você é do futuro? Digite um ano válido!')

Ano de nascimento: 2004
Você nasceu em 2004, tem 18 anos de idade em 2022.
Você deve se alistar esse ano.


##  <font color = 'red'> Desafio 040 - Aquele clássico da Média</font>

Crie um programa que leia duas notas de um aluno e calcule sua média, mostrando uma mensagem no final, de acordo com a média atingida.
- Média abaixo de 5.0: REPROVADO
- Média entre 5.0 e 6.9: RECUPERAÇÃO
- Média 7.0 ou superior: APROVADO

In [19]:
nota1 = float(input('Primeira nota: '))
nota2 = float(input('Segunda nota: '))
media = (nota1 + nota2) / 2

print(f"Tirando {nota1:.1f} e {nota2:.1f}, a média do aluno é {media:.1f}")
if 7 > media >= 5:
    print('O aluno está em RECUPERÃO.')
elif media < 5:
    print('O aluno está em REPROVADO.')
elif media >= 7:
    print('O aluno está em APROVADO.')

Primeira nota: 6.32
Segunda nota: 7.45
Tirando 6.3 e 7.5, a média do aluno é 6.9
O aluno está em RECUPERÃO.


##  <font color = 'red'> Desafio 041 - Categorias por idade</font>

A Confederação Nacional de Natação precisa de um programa que leia o ano de nascimento de um atleta e mostre sua categoria, de acordo com a idade:
- Até 9 anos: MIRIM
- Até 14 anos: INFANTIL
- Até 19 anos: JUNIOR
- Até 20 anos: SÊNIOR
- Acima: MASTER

In [23]:
from datetime import date

atual = date.today().year
nascimento = int(input('Ano de Nascimento: '))
idade = atual - nascimento

print(f'O atleta tem {idade} anos')
if idade <= 9:
    print('Classificação: MIRIM')
elif idade <= 14:
    print('Classificação: INFANTIL')
elif idade <= 19:
    print('Classificação: JUNIOR')
elif idade <= 25:
    print('Classificação: SÊNIOR')
else:
    print('Classificação: MASTER')

Ano de Nascimento: 2020
O atleta tem 4 anos
Classificação: MIRIM


##  <font color = 'red'> Desafio 042 - Analisando Triângulos v2.0</font>

Refaça o DESAFIO 035  dos tri^ngulos, acrescentando o recurso de mostrar que tipo de triângulo será formado:
 - Equilátero: todos os lados iguais;
 - Isósceles: dois lados iguais;
 - Escaleno: todos os lados diferentes.

In [13]:
r1 = float(input('Primeiro seguimento: '))
r2 = float(input('Segundo seguimento: '))
r3 = float(input('Terceiro seguimento: '))
if r1 < r2 + r3 and r2 < r1 + r3 and r3< r1 + r2:
    print('Os seguimentos acima PODEM FORMAR um triângulo ', end='')
    if r1 == r2 == r3:
        print('EQUILÁTERO')
    elif r1 != r2 != r3 != r1:
        print('ESCALENO')
    else:
        print('ISÓSCELES')
else:
    print('Os seguimentos acima NÃO PODEM FORMAR um triângulo!')

Primeiro seguimento: 4
Segundo seguimento: 2
Terceiro seguimento: 4
Os seguimentos acima PODEM FORMAR um triângulo ISÓSCELES


##  <font color = 'red'> Desafio 043 -  Índice de Massa Corporal (IMC)</font>

Desenvolva uma lógica que leia o peso e a altura de uma pessoa, calcule e mostre seu IMC de acrodo com a tabela abaixo:
- Abaixo de 18.5: Abaixo do peso
- Entre 18.5 e 25: Peso ideal
- Entre 25 e 30: Sobrepeso
- Entre 30 e 40: Obesidade
- Acima de 40: Obsesidade mórbida

In [24]:
peso = float(input('Qual é o seu peso em Kg? '))
altura = float(input('Qual é a sua altura em métros?' ))
imc = peso / (altura ** 2)
print(f'O IMC desta pessoa é de {imc:.2f}')

if imc < 18.5:
    print('Você está ABAIXO DO PESO normal.')
elif 18.5 <= imc < 25:
    print('PARABÉNS, você está na faixa de PESO NORMAL.')
elif 25 <= imc < 30:
    print('Você está em SOBREPESO.')
elif 30 <= imc < 40:
    print('Você está em OBESIDADE.')
elif imc >= 40:
    print('Você está em OBESIDADE MÓRBIDA, cuidado!')

Qual é o seu peso em Kg? 70
Qual é a sua altura em métros?1.69
O IMC desta pessoa é de 24.51
PARABÉNS, você está na faixa de PESO NORMAL.


##  <font color = 'red'> Desafio 044 - Gerenciador de Pagamentos</font>

Elabore um programa que calcule o valor a ser pago por um produto, considerando o seu preço normal e condição de pagamento:
- à vista dinheiro: 10% de desconto;
- à vista cartão: 5% de desconto;
- em até 2x no cartão: preço normal;
- em 3x ou mais no cartão: 20% de juros

In [43]:
loja = "LOJAS GUANABARA"
print(f'{loja:=^40}')

preco = float(input('Preço das compras: R$'))
print(''' FORMAS DE PAGAMENTO
[ 1 ] à vista dinheiro
[ 2 ] à vista cartão
[ 3 ] 2x no cartão
[ 4 ] 3x ou mais no cartão''')

op = int(input('Digite a forma de pagamento: '))
if op == 1:
    total  = preco - (preco * 10 /100)
elif op == 2:
    total  = preco - (preco * 5 /100)
elif op == 3:
    total  = preco
    parcela = total / 2
    print(f'Sua compra será parcelada em 2x de R${parcela:.2f} SEM JUROS.')
elif op == 4:
    total = preco + (preco * 20 / 100)
    totparc = int(input('Informe o número de parcelas: '))
    parcela = total / totparc
    print(f'Sua compra será parcelada em {totparc}x de R${parcela:.2f} COM JUROS')
else:
    total = preco
    print(f'Opção de pagamento inválida. Tente novamente!')
print(f'Sua compra de R${preco:.2f} vai custar R${total:.2f} no final.')


============LOJAS GUANABARA=============
Preço das compras: R$1000
 FORMAS DE PAGAMENTO
[ 1 ] à vista dinheiro
[ 2 ] à vista cartão
[ 3 ] 2x no cartão
[ 4 ] 3x ou mais no cartão
Digite a forma de pagamento: 7
Opção de pagamento inválida. Tente novamente!
Sua compra de R$1000.00 vai custar R$1000.00 no final.


##  <font color = 'red'> Desafio 045 - GAME  Pedra Papel e Tesoura</font>

Crie um programa que faça o computador jogar Jokenpô com você.

In [55]:
from random import randint
from time import sleep

itens = ('Pedra', 'Papel', 'Tesoura')
computador = randint(0, 2)
print('''Suas opções:
[ 0 ] PEDRA
[ 1 ] PAPEL
[ 2 ] TESOURA''')
jogador = int(input('Faça a sua jogada: '))


if 0 >= jogador < 3:    

    print('JO')
    sleep(1)
    print('KEN')
    sleep(1)
    print('PO!!!')
    sleep(1)

    print('-=' * 11)
    print(f'Computador jogou {itens[computador]}')
    print(f'Você jogou {itens[jogador]}')
    print('-=' * 11)

    if computador == 0: # computador jogou PEDRA
        if jogador == 0:
            print('EMPATE')
        elif jogador == 1:
            print('JOGADOR VENCE')
        elif jogador == 2:
            print('COMPUTADOR VENCE')       
    elif computador == 1: # computador jogou PAPEL
        if jogador == 0:
            print('COMPUTADOR VENCE')
        elif jogador == 1:
            print('EMPATE')
        elif jogador == 2:
            print('JOGADOR VENCE')
    elif computador == 2: # computador jogou TESOURA
        if jogador == 0:
            print('JOGADOR VENCE')
        elif jogador == 1:
            print('COMPUTADOR VENCE')
        elif jogador == 2:
            print('EMPATE')
else:
    print('JOGADA INVÁLIDA')
    

Suas opções:
[ 0 ] PEDRA
[ 1 ] PAPEL
[ 2 ] TESOURA
Faça a sua jogada: 3
JOGADA INVÁLIDA


##  <font color = 'red'> Desafio 046 - Contagem regressiva</font>

Faça um programa que mostre na tela uma contagem regressiva para o estouro de fogos de artifício, indo de 10 té 0, com uma pausa de 1 segundo entre eles.

In [2]:
from time import sleep

for cont in range(10, -1, -1):
    print(cont)
    sleep(1)
print('BUM!' 'BUM!' 'BUM!')


10
9
8
7
6
5
4
3
2
1
0
BUM!BUM!BUM!


##  <font color = 'red'> Desafio 047 - Contagem de pares</font>

Crie um programa que mostre na tela todos os números pares que estão no intervaldo entre 1 e 50.

In [10]:
for n in range(1, 51):
    # O print abaixo foi adicionado para verificar que são feitas 
    # duas iterações sem apresentar valor.
    print('.', end='') 
    if n % 2 ==0:
        print(n, end=' ')
print('Acabou.')


..2 ..4 ..6 ..8 ..10 ..12 ..14 ..16 ..18 ..20 ..22 ..24 ..26 ..28 ..30 ..32 ..34 ..36 ..38 ..40 ..42 ..44 ..46 ..48 ..50 Acabou.


In [11]:
# Alterado o inicio e passo do laço para diminuir a qtd de iterações.
for n in range(2, 51, 2): 
    print('.', end='') 
    if n % 2 ==0:
        print(n, end=' ')
print('Acabou.')


.2 .4 .6 .8 .10 .12 .14 .16 .18 .20 .22 .24 .26 .28 .30 .32 .34 .36 .38 .40 .42 .44 .46 .48 .50 Acabou.


##  <font color = 'red'> Desafio 048 - Soma ímpares múltiplos de três</font>

Faça um programa que calcule a soma entre todos os números ímpares que são múltiplos de três e que se encontram no intervalo de 1 até 500.

In [21]:
soma = 0 # Acumulador
cont = 0 # Contador
for c in range(1, 501, 2):
    if c % 3 == 0:
        cont += 1 # cont += 1 é igual a cont = cont + 1
        soma += c # soma += c é igual a soma = soma + c
print(f'A soma de todos os {cont} valores solicitados é {soma}.')


A soma de todos os 83 valores solicitados é 20667.


##  <font color = 'red'> Desafio 049 - Tabuada v.2.0</font>
Refaça o DESAFIO 9, mostrando a tabuada de um número que o usuário escolher, so que agora utilizando um laço <code>for</code>.




In [36]:
num = int(input("Digite um número para ver sua tabuada: "))
for c in range(0, 11):
    print(f'{num} x {c} = {num * c}')

Digite um número para ver sua tabuada: 6
6 x 0 = 0
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


##  <font color = 'red'> Desafio 050 - Soma dos pares</font>

Desenvolta um programa que leia seis números inteiros e mostre a soma apenas daqueles que forem pares. Se o valor digitado por ímpar, desconsidere-o.

In [48]:
soma = 0 # Acumulador
cont = 0 # Contador
for c in range(1, 7):
    num = int(input(f'Digite o {c}° valor:' ))    
    if num % 2 == 0:
        soma += num
        cont += 1
if cont == 0:
    print(f'Você não digitou nenhum número par.')
elif cont == 1:
    print(f'Você digitou {cont} número PAR que foi {soma}.')
elif cont > 1:
    print(f'Você digitou {cont} números PARES e a soma deles foi {soma}.')


Digite o 1° valor:1
Digite o 2° valor:2
Digite o 3° valor:3
Digite o 4° valor:4
Digite o 5° valor:5
Digite o 6° valor:6
Você digitou 3 números PARES e a soma deles foi 12.


##  <font color = 'red'> Desafio 051 - Progressão Aritmética</font>

Desenvolva um programa que leia o primeiro termo e a razão de uma PA . No final, mostre os 10 primeiros termos dessa progressão.

In [73]:
titulo = ' 10 TERMOS DE UMA PA '
print('='*40)
print(f'{titulo:=^40}')
print('='*40)

n = int(input(f'Primeiro Termo: '))
r = int(input(f'Razão: '))
dec = n + (10 - 1) * r
for c in range(n, dec + r, r):
    print(c, end=' --> ')
print('ACABOU!')

========= 10 TERMOS DE UMA PA ==========
Primeiro Termo: 25
Razão: 5
25 --> 30 --> 35 --> 40 --> 45 --> 50 --> 55 --> 60 --> 65 --> 70 --> ACABOU!


##  <font color = 'red'> Desafio 052 - Números primos</font>

Faça um programa que leia um número inteiro e diga se ele é ou não um número primo.

In [96]:
cont = 0 # Contador
num = int(input(f'Digite um número: '))
for c in range(1, num + 1):
    if num % c == 0:
        print('\033[33m', end=' ')
        cont += 1
    else:
        print('\033[31m', end=' ')
    print(c, end='')
print(f'\n\033[mO número {num} foi divisível {cont}° vezes.')
if cont == 2:
    print(f'E por isso ele É PRIMO!')
else:
    print(f'E por isso ele NÃO É PRIMO!')

Digite um número: 55
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
O número 55 foi divisível 4° vezes.
E por isso ele NÃO É PRIMO!


##  <font color = 'red'> Desafio 053 - Detector de Palíndromo </font>

Crie um programa que leia uma frase qualquer e diga se ela é um palíndro, desconsiderado os espaços.
Exemplos re palíndromo:
 - ANA
 - ARARA
 - APOS A SOPA
 - A SACADA DA CASA
 - A TORRE DA DERROTA
 - O LOBO AMA O BOLO
 - ANOTARAM A DATA DA MARATONA

In [111]:
# strip() retira os espaços antes e depois
# upper() deixa todas as letras maiúsculas
frase = str(input(f'Digite uma frase: ')).strip().upper()

# split() separa as palavras
palavras = frase.split()

# join() agrupa as palavras
junto = ''.join(palavras)

inverso = ''
for letra in range(len(junto) - 1, -1, -1):
    inverso += junto[letra]
print(f'O inverso de {junto} é {inverso}')
if inverso == junto:
    print('Temos um palíndromo!')
else:
    print('A frase digitada não é um palíndromo!')


Digite uma frase: nogueira
O inverso de NOGUEIRA é ARIEUGON
A frase digitada não é um palíndromo!


Fazendo o desafio 053 utilizando fatiamento.

In [114]:
frase = str(input(f'Digite uma frase: ')).strip().upper()

palavras = frase.split()

junto = ''.join(palavras)

inverso = junto[::-1] # Usando fatiamento
# o primeiro : diz que vai começar no início e 
# o segundo : diz que vai até o fim. 
# O -1 diz que vai fazer isso de trás para frente

print(f'O inverso de {junto} é {inverso}')
if inverso == junto:
    print('Temos um palíndromo!')
else:
    print('A frase digitada não é um palíndromo!')

Digite uma frase: arara
O inverso de ARARA é ARARA
Temos um palíndromo!


##  <font color = 'red'> Desafio 054 - Grupo da Maior Idade</font>

Crie um programa que leia o ano de nascimento de sete pessoas. No final, mostre quantas pessoas ainda não atingiram a maioridade e quantas já são maiores.

In [120]:
from datetime import date

atual = date.today().year
totMaior = 0
totMenor = 0
for pess in range(1, 8):
    nasc = int(input(f'Em que anos a {pess} pessoa nasceu?'))
    idade = atual - nasc
    if idade >= 21:
        totMaior += 1
    else:
        totMenor += 1
print(f'Ao todo tivemos {totMaior} pessoas maiores de idade')
print(f'E também tivemos {totMenor} pessoas menor de idade')


Em que anos a 1 pessoa nasceu?2000
Em que anos a 2 pessoa nasceu?1970
Em que anos a 3 pessoa nasceu?2005
Em que anos a 4 pessoa nasceu?1990
Em que anos a 5 pessoa nasceu?2010
Em que anos a 6 pessoa nasceu?1960
Em que anos a 7 pessoa nasceu?1940
Ao todo tivemos 5 pessoas maiores de idade
E também tivemos 2 pessoas menor de idade


##  <font color = 'red'> Desafio 055 - Maior e Menor da sequência</font>

Faça um programa que leia o peso de cinco pessoas. No final, mostre qual foi o maior e o menor peso lidos.

In [121]:
maior = 0
menor = 0
for p in range(1, 6):
    peso = float(input(f'Peso da {p}ª pessoa: '))
    if p == 1:
        maior = peso
        menor = peso
    else:
        if peso > maior:
            maior = peso
        if peso < menor:
            menor = peso
print(f'O maior peso lido foi de {maior}kg')
print(f'O menor peso lido foi de {menor}kg')


Peso da 1ª pessoa: 80
Peso da 2ª pessoa: 65.5
Peso da 3ª pessoa: 45.9
Peso da 4ª pessoa: 55
Peso da 5ª pessoa: 110.5
O maior peso lido foi de 110.5kg
O menor peso lido foi de 45.9kg


##  <font color = 'red'> Desafio 056 - Analisador Completo</font>

Desenvolva um programa que leia o nome, idade e sexo de 4 pessoas. No final do programa, mostre:
- A média de idade do grupo.
- Qual é o nome do homem mais velho.
- Quantas mulheres têm menos de 20 anos.

In [125]:
somaIdade = 0
mediaIdade = 0
maiorIdadeHomem = 0
nomeVelho = ''
totMulher20 = 0
for p in range(1, 5):
    print(f'----- {p}ª PESSOA -----')
    nome = str(input('Nome: ')).strip()
    idade = int(input('Idade: '))
    sexo = str(input('Sexo [M/F]')).strip().upper()    
    somaIdade += idade
    # if p = 1 and sexo in 'Mm':
    if p == 1 and sexo == 'M':
        maiorIdadeHomem = idade
        nomeVelho = nome
    # if sexo in 'Mm' and idade > maiorIdadeHomem:   
    if sexo == 'M' and idade > maiorIdadeHomem:
        maiorIdadeHomem = idade
        nomeVelho = nome
    # if sexo in 'Ff' and idade < 20:
    if sexo == 'F' and idade < 20:
        totMulher20 += 1
mediaIdade = somaIdade / 4
print(f'A média de idade do grupo é de {mediaIdade} anos.')
print(f'O home mais velho tem {maiorIdadeHomem} e se chama {nomeVelho}.')
print(f'Ao todo são {totMulher20} com menos de 20 anos.')


----- 1ª PESSOA -----
Nome: Jéssica
Idade: 23
Sexo [M/F]F
----- 2ª PESSOA -----
Nome: Cláudio
Idade: 12
Sexo [M/F]m
----- 3ª PESSOA -----
Nome: Pedro
Idade: 75
Sexo [M/F]m
----- 4ª PESSOA -----
Nome: Maria
Idade: 15
Sexo [M/F]f
A média de idade do grupo é de 31.25 anos.
O home mais velho tem 75 e se chama Pedro.
Ao todo são 1 com menos de 20 anos.


##  <font color = 'red'> Desafio 057 - Validação de Dados</font>

Faça um programa que leia o sexo de uma pessoa, mas só aceite os valores 'M' ou 'F'. Caso esteja errado, peça a digitação novamente até ter um valor correto.

In [126]:
sexo = str(input('Informe seu sexo: [M/F]')).strip().upper()[0] # [0] só pega a primeira letra
while sexo not in 'MF':
    sexo = str(input('Dados inválidos. Por favor, informe seu sexo: ')).strip().upper()[0]
print(f'Sexo {sexo} registrado com sucesso.')    

Informe seu sexo: [M/F]a
Dados inválidos. Por favor, informe seu sexo: b
Dados inválidos. Por favor, informe seu sexo: laksjdlkf
Dados inválidos. Por favor, informe seu sexo: jasldjflksjf
Dados inválidos. Por favor, informe seu sexo: macarrao
Sexo M registrado com sucesso.


##  <font color = 'red'> Desafio 058 - Jogo da Adivinhação</font>
Melhore o jogo do DESAFIO 028 onde o computador vai "pensar" em um número entre 0 e 10. Só que agora o jogador vai tentar adicinhar até acertar, mostrado no final quantos palpites foram necessário para vencer.

In [132]:
from random import randint

computador = randint(0, 10)
print('Sou seu computador... Acabei de pesar em um número entre 0 e 10.')
print('Será que você consegue adicinhar qual foi?')
acertou = False
palpites = 0 # Contador
while not acertou:
    jogador = int(input('Qual é o seu palpite? '))
    palpites += 1
    if jogador == computador:
        acertou = True
    else:
        if jogador < computador:
            print('Mais... Tente mais uma vez.')
        elif jogador > computador:
            print('Menos... Tente mais uma vez')
print(f'Acertou com {palpites} tentativas. Parabéns!')

Sou seu computador... Acabei de pesar em um número entre 0 e 10.
Será que você consegue adicinhar qual foi?
Qual é o seu palpite? 6
Menos... Tente mais uma vez
Qual é o seu palpite? 2
Mais... Tente mais uma vez.
Qual é o seu palpite? 5
Acertou com 3 tentativas. Parabéns!


##  <font color = 'red'> Desafio 059 - Criando um Menu de Opções</font>

Crie um programa que leia dois valores e mostre o seguinte memun para o usuário:

- [1] somar
- [2] multiplicar
- [3] maior
- [4] novos números
- [5] sair do programa

Seu programa deverá realizar a operação solicitada em cada caso.

In [134]:
from time import sleep

n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
op = 0
while op != 5:
    print('''
    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa''')
    op = int(input('>>>>>> Qual é a sua opção? '))
    if op == 1:
        soma = n1 + n2
        print(f'A soma entre {n1} + {n2} é {soma}.')
    elif op == 2:
        produto = n1 * n2
        print(f'O resultado de {n1} x {n2} é {produto}.')
    elif op == 3:
        if n1 > n2:
            maior = n1
        else:
            maior = n2
        print(f'Entre {n1} e {n2} o maior valore é {maior}.')
    elif op == 4:
        print('Informe os números novamente: ')
        n1 = int(input('Primeiro valor: '))
        n2 = int(input('Segundo valor: '))
    elif op == 5:
        print('Finalizando...')
    else:
        print('Opção inválida. Tente novamente.')
    print('=-=' * 10)
    sleep(1.5)
print('Fim do programa! Volte sempre!')

Primeiro valor: 7
Segundo valor: 8

    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa
>>>>>> Qual é a sua opção? 3
Entre 7 e 8 o maior valore é 8.
=-==-==-==-==-==-==-==-==-==-=

    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa
>>>>>> Qual é a sua opção? 4
Informe os números novamente: 
Primeiro valor: 6
Segundo valor: 0
=-==-==-==-==-==-==-==-==-==-=

    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa
>>>>>> Qual é a sua opção? 2
O resultado de 6 x 0 é 0.
=-==-==-==-==-==-==-==-==-==-=

    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa
>>>>>> Qual é a sua opção? 1
A soma entre 6 + 0 é 6.
=-==-==-==-==-==-==-==-==-==-=

    [1] somar
    [2] multiplicar
    [3] maior
    [4] novos números
    [5] sair do programa
>>>>>> Qual é a sua opção? 5
Finalizando...
=-==-==-==-==-==-==-==-==-==-=
Fim do programa! Volte

##  <font color = 'red'> Desafio 060 - Cálculo do Fatorial</font>

Faça um programa que leia um número qualquer e mostre o seu fatorial.

Ex.: 5! = 5 x 4 x 3 x 2 x 1 = 120

In [136]:
# Usando a biblioteca math

from math import factorial

n = int(input('Digite um número para calcular seu Fatorial: '))
f = factorial(n)
print(f'O fatorial de {n} é {f}')


Digite um número para calcular seu Fatorial: 5
O fatorial de 5 é 120


In [145]:
# Contruindo a lógica para calcular o fatorial

n = int(input('Digite um número para calcular seu Fatorial: '))
#c = n
f = 1
print(f'Calculado {n}! --> ', end='')
while n > 0:
    print(f'{n}', end='')
    print(' x ' if n > 1 else ' = ', end='')
    f *= n
    n -= 1

print(f'{f}')


Digite um número para calcular seu Fatorial: 5
Calculado 5! --> 5 x 4 x 3 x 2 x 1 = 120


##  <font color = 'red'> Desafio 061 - Progressão Aritmética</font>

Refaça o DESAFIO 051, lendo o primeiro termo e a razão de uma PA, mostrando os 10 primeiros termos da progressão usando a estrutura <code>while</code>.

In [151]:
titulo = ' 10 TERMOS DE UMA PA '
print('='*40)
print(f'{titulo:=^40}')
print('='*40)

n = int(input(f'Primeiro Termo: '))
r = int(input(f'Razão: '))
termo = n
cont = 1
while cont <= 10:
    print(f'{termo} --> ', end='')
    termo += r
    cont += 1
print('ACABOU')


========= 10 TERMOS DE UMA PA ==========
Primeiro Termo: 0
Razão: 5
0 --> 5 --> 10 --> 15 --> 20 --> 25 --> 30 --> 35 --> 40 --> 45 --> ACABOU


##  <font color = 'red'> Desafio 062 - Super Progressão Aritmética v3.0</font>

Melhore o DESAFIO 061, perguntado para o usuário se ele quer mostrar mais alguns termos. O programa encerra quando ele disser que quer mostrar 0 termos.

In [157]:
titulo = ' GERADOR DE PA '
print('='*40)
print(f'{titulo:=^40}')
print('='*40)

n = int(input(f'Primeiro Termo: '))
r = int(input(f'Razão: '))
termo = n
cont = 1
total = 0
mais = 10
while mais != 0:
    total += mais
    while cont <= total:
        print(f'{termo} --> ', end='')
        termo += r
        cont += 1
    print('PAUSA')
    mais = int(input('Quantos termos você quer mostrar a mais?' ))
print(f'Progressão finalizada com {total} termos mostrados.')


============ GERADOR DE PA =============
Primeiro Termo: 2
Razão: 2
2 --> 4 --> 6 --> 8 --> 10 --> 12 --> 14 --> 16 --> 18 --> 20 --> PAUSA
Quantos termos você quer mostrar a mais?2
22 --> 24 --> PAUSA
Quantos termos você quer mostrar a mais?0
Progressão finalizada com 12 termos mostrados.


##  <font color = 'red'> Desafio 063 - Sequência de Fibonacci</font>

Escreva um programa que leia um número n inteiro qualquer e mostre na tela os n primeiros elementos de uma Sequência de Fibonacci.

Ex.: 0 --> 1 --> 1 --> 2 --> 3 --> 5 --> 8

In [167]:
titulo = ' Sequência de Fibonacci '
print('='*40)
print(f'{titulo:=^40}')
print('='*40)

n = int(input('Quantos termos você quer mostrar? '))
t1 = 0
t2 = 1
print('~'*30)
print(f'{t1} -> {t2}', end='')
cont = 3
while cont <= n:    
    t3 = t1 + t2
    print(f' -> {t3}', end='')
    t1 = t2
    t2 = t3
    cont += 1
print(' -> FIM')


======== Sequência de Fibonacci ========
Quantos termos você quer mostrar? 6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0 -> 1 -> 1 -> 2 -> 3 -> 5 -> FIM


##  <font color = 'red'> Desafio 064 - Tratando vários valores</font>

Crie um programa que leia vários números inteiros pelo teclado. O programa só vai parar quanto o usuário digitar o valor 999, que é a condição de parada. No final, mostre quantos números foram digitados e qual foi a soma entre eles (desconsiderando o flag).

In [172]:
# num = 0
# cont = 0 # Contador
# soma = 0 # Acumulador
num = cont = soma = 0
num = int(input('Digite um número [999 para parar]: '))
while num != 999:
    soma += num
    cont += 1    
    num = int(input('Digite um número [999 para parar]: '))
print(f'Você digitou {cont} números e a soma entre eles foi {soma}')  

Digite um número [999 para parar]: 1
Digite um número [999 para parar]: 2
Digite um número [999 para parar]: 3
Digite um número [999 para parar]: 999
Você digitou 3 números e a soma entre eles foi 6


##  <font color = 'red'> Desafio 065 - Maior e menor valores</font>

Crie um programa que leia vários números inteiros pelo teclado. No final da execução, mostre a média entre todos os valores e qual foi o maior e menor valores lidos. O programa deve perguntar ao usuário se ele quer ou não continuar a digitar valores.

In [179]:
resp = str('S').upper().strip()
soma = qtd = media = maior = menor = 0
while resp == 'S':
    num = int(input('Digite um número: '))
    soma += num
    qtd += 1
    if qtd == 1:
        maior = menor = num
    else:
        if num > maior:
            maior = num
        if num < menor:
            menor = num    
    resp = str(input('Quer continuar? [S/N] ')).upper().strip()
media = soma / qtd
print(f'Você digitou {qtd} números e a média foi {media}')
print(f'O maior valor foi {maior} e o menor foi {menor}')


Digite um número: 4
Quer continuar? [S/N] s
Digite um número: 2
Quer continuar? [S/N] s
Digite um número: 1
Quer continuar? [S/N] s
Digite um número: 4
Quer continuar? [S/N] n
Você digitou 4 números e a média foi 2.75
O maior valor foi 4 e o menor foi 1


##  <font color = 'red'> Desafio 066 - Vários números com flags</font>

Crie um programa que leia vários números inteiros pelo teclado. O programa só vai parar quando o usuário digitar o valor 999, que é a condição de parada. No final, mostre quantos números foram digitados e qual foi a soma entre eles (desconsiderando o flag).

In [181]:
soma = cont = 0
while True:
    num = int(input('Digite um valor (999 para parar): '))
    if num == 999:
        break
    cont += 1
    soma += num
print(f'A soma dos {cont} valores foi {soma}!')

Digite um valor (999 para parar): 3
Digite um valor (999 para parar): 9
Digite um valor (999 para parar): 1
Digite um valor (999 para parar): 999
A soma dos 3 valores foi 13!


##  <font color = 'red'> Desafio 067 - Tabuada v3.0</font>

Faça um programa que mostre a tabuada de vários números, um de cada vez, para cada valor digitado pelo usuário. O programa será interrompido quando o número solicitado for negativo.

In [189]:
while True:
    num = int(input('Quer ver a tabuada de que valor?' ))   
    print('-'* 30)
    if num < 0:
        break
    for n in range(0, 11):        
        print(f'{num} x {n} = {num * n}')
    print('-'* 30)
print('PROGRAMA TABUADA ENCERRADO. Volte Sempre!')
        

Quer ver a tabuada de que valor?6
------------------------------
6 x 0 = 0
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
------------------------------
Quer ver a tabuada de que valor?-5
------------------------------
PROGRAMA TABUADA ENCERRADO. Volte Sempre!


##  <font color = 'red'> Desafio 068 - Jogo do Par ou Ímpar</font>

Faça um programa que jogue par ou ímpar com o computador. O jogo só será interrompido quando o jogador PERDER, mostrando o total de vitórias consecutivas que ele conquistou no final do jogo.

In [195]:
from random import randint

v = 0
while True:
    jogador = int(input('Diga um valor: '))
    computador = randint(0, 10)
    total = jogador + computador
    tipo = ' '
    while tipo not in 'PI':
        tipo = str(input('Par ou Ímpar? [P/I] ')).strip().upper()[0]
    print(f'Você jogou {jogador} e o computador {computador}. Total de {total} ', end='')
    print('DEU PAR' if total % 2 == 0 else 'DEU IMPAR')
    if tipo == 'P':
        if total % 2 == 0:
            print('Você VENCEU!')
            v += 1
        else:
            print('Você PERDEU!')
            break
    elif tipo == 'I':
        if total % 2 == 1:
            print('Você VENCEU!')
            v += 1
        else:
            print('Você PERDEU!')
            break
    print('Vamos jogar novamente...')

Diga um valor: 3
Par ou Ímpar? [P/I] p
Você jogou 3 e o computador 7. Total de 10 DEU PAR
Você VENCEU!
Vamos jogar novamente...
Diga um valor: 3
Par ou Ímpar? [P/I] p
Você jogou 3 e o computador 0. Total de 3 DEU IMPAR
Você PERDEU!


##  <font color = 'red'> Desafio 069 - Análise de dados do grupo</font>

Crie um programa que leia a idade e o sexo de várias pessoas. A cada pessoa cadastrada, o programa deverá perguntar se o usuário quer ou não continuar. No final, mostre:

 - Quantas pessoas tem mais de 18 anos.
 - Quantos homens foram cadastrados.
 - Quantas mulheres tem menos de 20 anos.

In [203]:
tot18 = totH = totM20 = 0
while True:
    idade = int(input('Idade: '))
    sexo = ' '
    while sexo not in 'MF':
        sexo = str(input('Sexo: [M/F] ')).strip().upper()[0]
    if idade > 18:
        tot18 += 1
    if sexo == 'M':
        totH += 1
    if sexo == 'F' and idade < 20:
        totM20 += 1    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    if resp == 'N':
        break
print(f'Total de pessoas com mais de 18 anos: {tot18}.')
print(f'Ao todos temos {totH} homens cadastrados.')
print(f'E temos {totM20} mulheres com menos de 20 anos.')


Idade: 22
Sexo: [M/F] m
Quer continuar? [S/N] s
Idade: 16
Sexo: [M/F] f
Quer continuar? [S/N] s
Idade: 45
Sexo: [M/F] f
Quer continuar? [S/N] s
Idade: 12
Sexo: [M/F] m
Quer continuar? [S/N] n
Total de pessoas com mais de 18 anos: 2.
Ao todos temos 2 homens cadastrados.
E temos 1 mulheres com menos de 20 anos.


##  <font color = 'red'> Desafio 070 - Estatísticas de produtos</font>

Crie um programa que leia o nome e o preço de vários produtos. O programa deverá perguntar se o usuário vai continuar. No final, mostre:

- Qual é o total gasto na compra.
- Quantos produtos custam mais de 1.000,00 reais
- Qual é o nome do produto mais barato

In [211]:
total = totMil = menor = cont = 0
barato = ''
while True:
    produto = str(input('Nome do produto: '))
    preco = float(input('Preço: R$ '))
    cont += 1
    total += preco
    if preco > 1000:
        totMil += 1    
    if cont == 1 or preco < menor:
        menor = preco
        barato = produto
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    if resp == 'N':
        break
print('{:-^40}'.format(' FIM DO PROGRAMA'))
print(f'O total da compra foi R$ {total:.2f}.')
print(f'Temos {totMil} produtos custando mais de R$ 1.000,00.')
print(f'O produto mais barato foi {barato} que custa R$ {menor:.2f}.')


Nome do produto: Borracha
Preço: R$ 5
Quer continuar? [S/N] Caneta
Quer continuar? [S/N] s
Nome do produto: Caneta
Preço: R$ 10
Quer continuar? [S/N] s
Nome do produto: Notebook
Preço: R$ 1500
Quer continuar? [S/N] n
------------ FIM DO PROGRAMA------------
O total da compra foi R$ 1515.00.
Temos 1 produtos custando mais de R$ 1.000,00.
O produto mais barato foi Borracha que custa R$ 5.00.


##  <font color = 'red'> Desafio 071 - Caixa Eletrônico</font>

Crie um programa que simule o funcionamento de um caixa eletônico. No início, pergunte ao usuário qual será o valor a ser sacado (número inteiro) e o programa vai informar quantas cédulas de cada valor serão entregues.
Obs.: Considere que o caixa possui cédulas de 50, 20 e 1.

In [7]:
print('=' * 30)
print('{:^30}'.format('BANCO CEV'))
print('=' * 30)
valor = int(input('Que valor você que rsacar? R$'))
total = valor
ced = 50
totced = 0
while True:
    if total >= ced:
        total -= ced
        totced += 1
    else:
        if totced > 0:
            print(f'Total de {totced} cédulas de R${ced}')
        if ced == 50:
            ced = 20
        elif ced == 20:
            ced = 10
        elif ced == 10:
            ced = 1
        totced = 0
        if total == 0:
            break
print('=' * 30)
print('Volte sempre ao BANCO CEV! Tenha um bom dia!')


          BANCO CEV           
Que valor você que rsacar? R$122
Total de 2 cédulas de R$50
Total de 1 cédulas de R$20
Total de 2 cédulas de R$1
Volte sempre ao BANCO CEV! Tenha um bom dia!


# <font color = 'green'><a name="Mundo3">Mundo 3</font>

##  <font color = 'red'> Desafio 072 - Número por extenso</font>
Crie um programa que tenha uma tupla totalmente preenchida com uma contagem por extenso, de zero até vinte.</br>
Seu programa deverá ler um número pelo teclado (entre 0 e 20) e mostra-lo por extenso.

In [9]:
cont = ('zero', 'um', 'dois', 'três', 'quatro', 'cinco', 
       'seis', 'sete', 'oito', 'nove', 'dez',
       'onze', 'doze', 'treze', 'catorze', 'quinze',
       'dezesseis', 'dezessete', 'dezoito', 'dezenove', 'vinte')
while True:
    num = int(input('Digite um número entre 0 e 20: '))
    if 0 <= num <= 20:
        break
    print('Tente novamente.', end='')
print(f'Você digitou o número {cont[num]}')


Digite um número entre 0 e 20: 30
Tente novamente.Digite um número entre 0 e 20: 50
Tente novamente.Digite um número entre 0 e 20: 100
Tente novamente.Digite um número entre 0 e 20: 5
Você digitou o número cinco


##  <font color = 'red'> Desafio 073 - Tuplas com Times de Futebol</font>
Crie uma tupla preenchida com os 20 primeitos colocado da Tabela do Campeonato Brasileiro de Futebol, na ordem de colocação. Depois mostre:
- A) Apenas os 5 primeiros colocados.
- B) Os últimos 4 colocados da tabela.
- C) Uma lista com os times em ordem alfabética.
- D) Em que posição na tabela está o time da Chapecoense?

In [18]:
times = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio',
        'Cruzeiro', 'Flamento', 'Vasco', 'Chapecoense',
        'Atlêtico', 'Botafogo', 'Atlêtico-PR', 'Bahia',
        'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória',
        'Coritiba', 'Avaí', 'Ponte Preta', 'Atlêtico-GO',
        )
print('-=' * 15)
print(f'Lista de Times do Brasileirão: {times}')
# for t in times:
#     print(t)
print('-=' * 15)
print(f'Os 5 primeiros são: {times[0:5]}')
print('-=' * 15)
print(f'Os 4 últimos: {times[-4:]}')
print('-=' * 15)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 15)
print(f'O Chapecoense está na {times.index("Chapecoense")+1}ª posição')


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Lista de Times do Brasileirão: ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamento', 'Vasco', 'Chapecoense', 'Atlêtico', 'Botafogo', 'Atlêtico-PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlêtico-GO')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 5 primeiros são: ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 4 últimos: ('Coritiba', 'Avaí', 'Ponte Preta', 'Atlêtico-GO')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Times em ordem alfabética: ['Atlêtico', 'Atlêtico-GO', 'Atlêtico-PR', 'Avaí', 'Bahia', 'Botafogo', 'Chapecoense', 'Corinthians', 'Coritiba', 'Cruzeiro', 'EC Vitória', 'Flamento', 'Fluminense', 'Grêmio', 'Palmeiras', 'Ponte Preta', 'Santos', 'Sport Recife', 'São Paulo', 'Vasco']
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O Chapecoense está na 8ª posição


##  <font color = 'red'> Desafio 074 - Maior e menor valores em Tupla</font>
Crie um programa que vai gerar cinco números aleatórios e colocar em uma tupla.</br>
Depois disso, mostre a listagem de números gerados e também indique o menor e o maior valor que estão na tupla.

In [26]:
from random import randint

numeros = (randint(1, 10), randint(1, 10), randint(1, 10),
          randint(1, 10), randint(1, 10))
print('Os valores sorteados foram: ', end='')
for n in numeros:
    print(f'{n}', end=' ')
print(f'\nO maior valor sorteado foi {max(numeros)}')
print(f'O menor valor sorteado foi {min(numeros)}')


Os valores sorteados foram: 5 1 2 9 5 
O maior valor sorteado foi 9
O menor valor sorteado foi 1


##  <font color = 'red'> Desafio 075 - Análise de dados em uma Tupla</font>
Desenvolva um programa que leia quatro valores pelo teclado e guarde-os em uma tupla. No final, mostre:
- A) Quantas vezes apareceu o valor 9.
- B) Em que posição foi digitado o primeiro valor 3.
- C) Quais foram os números pares.

In [35]:
num = (int(input('Digite um número: ')),
      int(input('Digite outro número: ')),
      int(input('Digite mais um número: ')),
      int(input('Digite o último número: ')),)
print('-=' * 30)
print(f'Você digitou os valores {num}.')
print(f'O valor 9 apareceu {num.count(9)} vezes.')
if 3 in num:
    print(f'O valor 3 apareceu na {num.index(3)+1}ª posição.')
else:
    print('O valor 3 não foi digitado em nenhuma posição.')
print('Os valores pares digitados foram ', end='')
for n in num:
    if n % 2 == 0:
        print(n, end=' ')


Digite um número: 2
Digite outro número: 4
Digite mais um número: 5
Digite o último número: 7
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou os valores (2, 4, 5, 7)
O valor 9 apareceu 0 vezes
O valor 3 não foi digitado em nenhuma posição
Os valores pares digitados foram 2 4 

##  <font color = 'red'> Desafio 076 - Lista de Preços com Tupla</font>
Crie um programa que tenha uma tupla única com nomes de produtos e seus respectivos preços, na sequência.</br>
No final, mostre uma listagem de preços, organizando os dados em forma tabular.

In [39]:
listagem = ('Lápis', 1.75, 
            'Borracha', 2,
            'Caderno', 15.90,
            'Estojo', 25,
            'Transferidor', 4.20,
            'Compasso', 9.99,
            'Mochila', 120.32,
            'Canetas', 22.30,
            'Livro', 34.90)
print('-' * 40)
print(f'{"LISTAGEM DE PREÇOS":^40}')
print('-' * 40)
for pos in range(0, len(listagem)):
    if pos % 2 == 0:
        print(f'{listagem[pos]:.<30}', end='')
    else:
        print(f'R${listagem[pos]:>7.2f}')
print('-' * 40)

----------------------------------------
           LISTAGEM DE PREÇOS           
----------------------------------------
Lápis.........................R$   1.75
Borracha......................R$   2.00
Caderno.......................R$  15.90
Estojo........................R$  25.00
Transferidor..................R$   4.20
Compasso......................R$   9.99
Mochila.......................R$ 120.32
Canetas.......................R$  22.30
Livro.........................R$  34.90
----------------------------------------


##  <font color = 'red'> Desafio 077 - Contando vogais em Tuplas</font>
Crie um programa que tenha um tupla com várias palavras (não usar acentos). Depois disso, você deve mostrar, para cada palavra, quais são as suas vogais.

In [40]:
palavras = ('aprender', 'programar', 'linguagem', 'python', 
            'curso', 'gratis', 'estudar', 'praticar',
            'trabalhar', 'mercado', 'programador', 'futuro')
for p in palavras:
    print(f'\nNa palavra {p.upper()} temos: ', end='')
    for letra in p:
        if letra.lower() in 'aeiou':
            print(letra, end=' ')



Na palavra APRENDER temos: a e e 
Na palavra PROGRAMAR temos: o a a 
Na palavra LINGUAGEM temos: i u a e 
Na palavra PYTHON temos: o 
Na palavra CURSO temos: u o 
Na palavra GRATIS temos: a i 
Na palavra ESTUDAR temos: e u a 
Na palavra PRATICAR temos: a i a 
Na palavra TRABALHAR temos: a a a 
Na palavra MERCADO temos: e a o 
Na palavra PROGRAMADOR temos: o a a o 
Na palavra FUTURO temos: u u o 

##  <font color = 'red'> Desafio 078 - Maior e Menor valores ne Lista</font>
Faça um programa que leia 5 valores numéricos e guarde-os em uma lista.</br>
No final, mostre qual foi o maior e menor valores digitado e as suas respectivas posições na lista.

In [43]:
listaNum = []
maior = 0
menor = 0
for c in range(0, 5):
    listaNum.append(int(input(f'Digite um valor para a posição {c}: ')))
    if c == 0:
        maior = menor = listaNum[c]
    else:
        if listaNum[c] > maior:
            maior = listaNum[c]
        if listaNum[c] < menor:
            menor = listaNum[c]
print('-=' * 30)
print(f'Você digitou os valores: {listaNum}')
print(f'O maior valor digitado foi {maior} nas posições: ', end='')
for i, v in enumerate(listaNum):
    if v == maior:
        print(f'{i}... ', end='')
print()
print(f'O menor valor digitado foi {menor} nas posições: ', end='')
for i, v in enumerate(listaNum):
    if v == menor:
        print(f'{i}... ', end='')
print()


Digite um valor para a posição 0: 1
Digite um valor para a posição 1: 8
Digite um valor para a posição 2: 8
Digite um valor para a posição 3: 2
Digite um valor para a posição 4: 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou os valores: [1, 8, 8, 2, 1]
O maior valor digitado foi 8 nas posições: 1... 2... 
O menor valor digitado foi 1 nas posições: 0... 4... 


##  <font color = 'red'> Desafio 079 - Valores únicos em uma Lista</font>
Crie um programa onde o usuário possa digitar vários valores numéricos e cadastre-os em uma lista. Caso o número já exista la dentro, ele não será adicionado.</br>
No final, serão exibidos todos os valores únicos, digitados, em ordem crescente.

In [47]:
numeros = list()
while True:
    n = int(input('Digite um valor: '))
    if n not in numeros:
        numeros.append(n)
        print('Valor adicionado com sucesso...')
    else:
        print('Valor duplicado! Não vou adicionar...')
    r = str(input('Quer continuar? [S/N] '))
    if r in 'Nn':
        break
print('-=' * 30)
numeros.sort()
print(f'Você digitou os valores {numeros}.')


Digite um valor: 9
Valor adicionado com sucesso...
Quer continuar? [S/N] s
Digite um valor: 7
Valor adicionado com sucesso...
Quer continuar? [S/N] s
Digite um valor: 4
Valor adicionado com sucesso...
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou os valores [4, 7, 9].


##  <font color = 'red'> Desafio 080 - Lista ordenada sem repetições</font>
Crie um programa onde o usuário possa digitar cinco valores numéricos e cadastre-os em uma lista, já na posição correta de inserção (sem usar o sort()).</br>
No final, mostre a lista ordenada na tela.

In [50]:
lista = []
for c in range(0, 5):
    n = int(input('Digite um valor: '))
    if c == 0 or n > lista[-1]:
        lista.append(n)
        print('Adicionado ao final da lista...')
    else:
        pos = 0
        while pos < len(lista):
            if n <= lista[pos]:
                lista.insert(pos, n)
                print(f'Adicionado na posição {pos} da lista...')
                break
            pos += 1
print('-=' * 30)
print(f'Os valores digitados em ordem foram {lista}')

Digite um valor: 8
Adicionado ao final da lista...
Digite um valor: 1
Adicionado na posição 0 da lista...
Digite um valor: 7
Adicionado na posição 1 da lista...
Digite um valor: 10
Adicionado ao final da lista...
Digite um valor: 0
Adicionado na posição 0 da lista...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os valores digitados em ordem foram [0, 1, 7, 8, 10]


##  <font color = 'red'> Desafio 081 - Extraindo dados de uma lista</font>
Crie um programa que vai ler vários números e colocar em uma lista.</br>
Depois disso, motre:
- A) Quantos números foram digitados.
- B) A lista de valores, ordenada de forma decrescente.
- C) Se o valor 5 foi digitado e está ou não na lista.

In [52]:
valores = []
while True:
    valores.append(int(input('Digite um valor: ')))
    resp = str(input('Quer continuar [S/N] '))
    if resp in 'Nn':
        break
print('-=' * 30)
print(f'Você digitou {len(valores)} elementos.')
valores.sort(reverse=True)
print(f'Os valores em ordem decrescente são {valores}.')
if 5 in valores:
    print('O valor 5 faz parte da lista!')
else:
    print('O valor 5 não foi encontrado na lista!')

Digite um valor: 3
Quer continuar [S/N] s
Digite um valor: 9
Quer continuar [S/N] s
Digite um valor: 6
Quer continuar [S/N] s
Digite um valor: 4
Quer continuar [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou 4 elementos.
Os valores em ordem decrescente são [9, 6, 4, 3].
O valor 5 não foi encontrado na lista!


##  <font color = 'red'> Desafio 082 - Dividindo valores em várias listas</font>
Crie um programa que vai ler vários números e colocar em uma lista.

Depois disso, crie duas listas extras que vão conter apenas os valores pares e os valores ímpares digitados, respectivamente.</br>

Ao final, mostre o conteúdo das três listas geradas.

In [ ]:
num = list()
pares = list()
impares = list()
while True:
    num.append(int(input('Digite um número: ')))
    resp = str(input('Quer continuar? [S/N] '))
    if resp in 'Nn':
        break
for i, v in enumerate(num):
    if v % 2 == 0:
        pares.append(v)
    elif v % 2 == 1: # poderia ser um else
        impares.append(v)
print('-=' * 30)
print(f'A lista completa é {num}')
print(f'A lista de pares é {pares}')
print(f'A lista de imperes é {pares}')


##  <font color = 'red'> Desafio 083 - Validando Expressões Matemáticas</font>
Crie um programa onde o usuário digite uma expressão qualquer que use parênteses. Seu aplicativo deverá analisar se a expressão passada está com os parênteses abertos e fechados na ordem correta.

In [3]:
expr = str(input('Digite a expressão: '))
pilha = []
for simb in expr:
    if simb == '(':
        pilha.append('(')
    elif simb == ')':
        if len(pilha) > 0:
            pilha.pop() # Remove o último elemento
        else:
            pilha.append(')')
            break
if len(pilha) == 0:
    print('Sua expressão está válida!')
else:
    print('Sua expressão está errada!')


Digite a expressão: (a+b)(a(4+3)*2)(c
Sua expressão está errada!


##  <font color = 'red'> Desafio 084 - Lista composta e análise de dados</font>
Faça um programa que leia nome e peso de várias pessoas, guardando tudo em uma lista. No final, mostre:
- A) Quantas pessoas foram cadastradas;
- B) Uma listagem com as pessoas mais pesadas;
- C) Uma listagem com as pessoas mais leves;

In [10]:
temp = []
princ = []
mai = men = 0
while True:
    temp.append(str(input('Nome: ')))
    temp.append(float(input('Peso: ')))
    if len(princ) == 0:
        mai = men = temp[1]
    else:
        if temp[1] > mai:
            mai = temp[1]
        if temp[1] < men:
            men = temp[1]
    princ.append(temp[:])
    temp.clear()
    resp = str(input('Quer continuar? [S/N] '))
    if resp in 'Nn':
        break
print('-=' * 30)
# print(f'Os dados foram {princ}')
print(f'Ao todo, você cadastrou {len(princ)} pessoas.')
print(f'O maior peso foi {mai}Kg. Peso de', end='')
for p in princ:
    if p[1] == mai:
        print(f'[{p[0]}]', end='')
print()
print(f'O menor peso foi {men}Kg. Peso de', end='')
for p in princ:
    if p[1] == men:
        print(f'[{p[0]}]', end='')
print()
      

Nome: Mario
Peso: 90
Quer continuar? [S/N] s
Nome: Ana
Peso: 75
Quer continuar? [S/N] s
Nome: Pedro
Peso: 80
Quer continuar? [S/N] s
Nome: Maria
Peso: 90
Quer continuar? [S/N] S
Nome: Clara
Peso: 75
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Ao todo, você cadastrou 5 pessoas.
O maior peso foi 90.0Kg. Peso de[Mario][Maria]
O menor peso foi 75.0Kg. Peso de[Ana][Clara]


##  <font color = 'red'> Desafio 085 - Listas com pares e ímpares</font>
Cria um programa onde o usuário possa digitar sete valores numéricos e cadastre-os em uma lista única que mantenha separados os valores pares e ímpares. No final, mostre os valores pares e ímpares em ordem crescente.

In [15]:
num = [[], []]
valor = 0
for c in range(1, 8):
    valor = int(input('Digite o {c}° valor: '))
    if valor % 2 == 0:
        num[0].append(valor)
    else:
        num[1].append(valor)
print('-=' * 30)
num[0].sort()
num[1].sort()
print(f'O valores pares digitados foram: {num[0]}')
print(f'O valores ímpares digitados foram: {num[1]}')

Digite o {c}° valor: 9
Digite o {c}° valor: 2
Digite o {c}° valor: 4
Digite o {c}° valor: 8
Digite o {c}° valor: 7
Digite o {c}° valor: 5
Digite o {c}° valor: 0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O valores pares digitados foram: [0, 2, 4, 8]
O valores ímpares digitados foram: [5, 7, 9]


##  <font color = 'red'> Desafio 086 - Matriz em Python</font>
Crie um programa que crie uma matriz de dimensão 3x3 e preencha com valores lidos pelo teclado.</br>

No final, mostre a matriz na tela, com a formatação correta.

In [16]:
matriz = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for l in range(0, 3):
    for c in range(0, 3):
        matriz[l][c] = int(input(f'Digite um valor para [{l}], [{c}]: '))
print('-=' * 30)
for l in range(0, 3):
    for c in range (0, 3):
        print(f'[{matriz[l][c]:^5}]', end='')
    print()
    

Digite um valor para [0], [0]: 11
Digite um valor para [0], [1]: 22
Digite um valor para [0], [2]: 33
Digite um valor para [1], [0]: 44
Digite um valor para [1], [1]: 55
Digite um valor para [1], [2]: 66
Digite um valor para [2], [0]: 77
Digite um valor para [2], [1]: 88
Digite um valor para [2], [2]: 99
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ 11  ][ 22  ][ 33  ]
[ 44  ][ 55  ][ 66  ]
[ 77  ][ 88  ][ 99  ]


##  <font color = 'red'> Desafio 087 - Mais sobre Matriz em Python </font>
Aprimore o desafio anterior, mostra no final:
- A) A soma de todos os valores pares digitados;
- B) A soma dos valores da terceira coluna.
- C) O maoior valor da segunda linha.

In [17]:
matriz = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
spar = mai = scol = 0
for l in range(0, 3):
    for c in range(0, 3):
        matriz[l][c] = int(input(f'Digite um valor para [{l}], [{c}]: '))
print('-=' * 30)
for l in range(0, 3):
    for c in range (0, 3):
        print(f'[{matriz[l][c]:^5}]', end='')
        if matriz[l][c] % 2 == 0:
            spar += matriz[l][c]
    print()
print('-=' * 30)
print(f'A soma dos valores pares é {spar}.')
for l in range(0,3):
    scol += matriz[l][2]
print(f'A soma dos valores da terceira coluna é {scol}.')
for c in range(0, 3):
    if c == 0:
        mai = matriz[1][c]
    elif matriz[1][c] > mai:
        mai = matriz[1][c]
print(f'O maior valor da segunda linha é {mai}')

Digite um valor para [0], [0]: 1
Digite um valor para [0], [1]: 2
Digite um valor para [0], [2]: 3
Digite um valor para [1], [0]: 4
Digite um valor para [1], [1]: 5
Digite um valor para [1], [2]: 6
Digite um valor para [2], [0]: 7
Digite um valor para [2], [1]: 8
Digite um valor para [2], [2]: 9
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  1  ][  2  ][  3  ]
[  4  ][  5  ][  6  ]
[  7  ][  8  ][  9  ]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A soma dos valores pares é 20.
A soma dos valores da terceira coluna é 18.
O maior valor da segunda linha é 6


##  <font color = 'red'> Desafio 088 - Palpites para a Mega Sena</font>
Faça um programa que ajude um jogador da MEGA SENA a criar palpites. O programa vai perguntar quantos jogos serão gerados e vai sortear 6 números entre 1 a 60 para cada jogo, cadastrando tudo em uma lista composta.

In [43]:
from random import randint
from time import sleep

print('-' * 30)
print('{:^30}'.format('JOGA NA MEGA SENA'))
print('-' * 30)
quant = int(input('Quantos jogos você quer que eu sorteie? '))
lista = list()
jogos = list()
tot = 1
while tot <= quant:
    cont = 0
    while True:
        num = randint(1, 60)
        if num not in lista:
            lista.append(num)
            cont += 1
        if cont >= 6:
            break
    lista.sort()
    jogos.append(lista[:])
    lista.clear()
    tot += 1
print('-=' *3, f'SORTEANDO {quant} JOGOS', '-=' * 3)
for i, l in enumerate(jogos):
    print(f'Jogo {i+1}: {l}')
    sleep(1)
print('-=' * 5, 'BOA SORTE!', '-=' * 5)


------------------------------
      JOGA NA MEGA SENA       
------------------------------
Quantos jogos você quer que eu sorteie? 5
-=-=-= SORTEANDO 5 JOGOS -=-=-=
Jogo 1: [15, 38, 49, 52, 55, 60]
Jogo 2: [2, 29, 32, 37, 38, 49]
Jogo 3: [6, 9, 18, 21, 26, 44]
Jogo 4: [4, 6, 8, 17, 20, 43]
Jogo 5: [2, 4, 7, 25, 39, 49]
-=-=-=-=-= BOA SORTE! -=-=-=-=-=


##  <font color = 'red'> Desafio 089 - Boletim com listas compostas</font>
Crie um programa que leia nome e duas notas de vários alunos e guarde tudo em uma lista composta. No final, mostre um boletim contendo a média de cada um e permita que o usuário possa mostrar as notas de cada aluno individualmente.

In [46]:
ficha = list()
while True:
    nome = str(input('Nome: '))
    nota1 = float(input('Nota 1: '))
    nota2 = float(input('Nota 2: '))
    media = (nota1 + nota2) / 2
    ficha.append([nome, [nota1, nota2], media])
    resp = str(input('Quer continuar? [S/N]' ))
    if resp in 'Nn':
        break
print('-=' * 30)
print(f'{"No":<4}{"NOME":<10}{"MÉDIA":>8}')
print('-=' * 30)
for i, a in enumerate(ficha):
    print(f'{i:<4}{a[0]:<10}{a[2]:>8.1f}')
while True:
    print('-' * 30)
    opc = int(input('Mostra notas de qual aluno? (999 interrompe): '))
    if opc == 999:
        print('FINALIZANDO...')
        break
    if opc <= len(ficha) -1:
        print(f'Notas de {ficha[opc][0]} são {ficha[opc][1]}')
print('<<< VOLTE SEMPRE >>>')

Nome: Ana
Nota 1: 9.5
Nota 2: 10
Quer continuar? [S/N]s
Nome: Gustavo
Nota 1: 2.5
Nota 2: 4
Quer continuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
No  NOME         MÉDIA
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0   Ana            9.8
1   Gustavo        3.2
-----------------------------------
Mostra notas de qual aluno? (999 interrompe): 1
Notas de Gustavo são [2.5, 4.0]
-----------------------------------
Mostra notas de qual aluno? (999 interrompe): 999
FINALIZANDO...
<<< VOLTE SEMPRE >>>


##  <font color = 'red'> Desafio 090 - Dicionário em Python</font>
Faça um programa que leia nome e média de um aluno, guardando também a situação em um dicionário. No final, mostre o conteúdo da estutura na tela

In [47]:
aluno = dict() # ou aluno = {}
aluno['nome'] = str(input('Nome: '))
aluno['media'] = float(input(f'Média de {aluno["nome"]}: '))
if aluno['media'] >= 7:
    aluno['situação'] = 'Aprovado'
elif 5 <= aluno['media'] < 7:
    aluno['situação'] = 'Recuperação'
else:
    aluno['situação'] = 'Reprovado'
print('-=' * 30)
for k, v in aluno.items():
    print(f' - {k} é igual a {v}')
    

Nome: Gustavo
Média de Gustavo: 4.2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 - nome é igual a Gustavo
 - media é igual a 4.2
 - situação é igual a Reprovado


##  <font color = 'red'> Desafio 091 - Jogo de Dados em Python</font>
Crie um programa onde 4 jogadores joguem um dado e tenham resultados aleatórios. Guarde esses resultados em um dicionário. No final, coloque esse dicionário em ordem, sabendo que o vencedor tirou o maoior número no dado.

In [57]:
from random import randint
from time import sleep
from operator import itemgetter

jogo = {'jogador1': randint(1, 6),
        'jogador2': randint(1, 6),
        'jogador3': randint(1, 6),
        'jogador4': randint(1, 6)}
ranking = list()
print('Valores sorteados: ')
for k, v in jogo.items():
    print(f'{k} tirou {v} no dado.')
    sleep(1)
ranking = sorted(jogo.items(), key=itemgetter(1), reverse=True)
print('-=' * 30)
print('== RANKING DOS JOGADORES ==')
for i, v in enumerate(ranking):
    print(f'  {i+1}° lugar: {v[0]} com {v[1]}.')

Valores sorteados: 
jogador1 tirou 1 no dado.
jogador2 tirou 3 no dado.
jogador3 tirou 4 no dado.
jogador4 tirou 6 no dado.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
== RANKING DOS JOGADORES ==
  1° lugar: jogador4 com 6.
  2° lugar: jogador3 com 4.
  3° lugar: jogador2 com 3.
  4° lugar: jogador1 com 1.


##  <font color = 'red'> Desafio 092 - Cadastro de Trabalhador em Python</font>
Crie um programa que leia nome, ano de nascimento e carteira de trabalho e cadastre-os (com idade) em um dicionário se por acaso a CTPS for diferente de ZERO, o dicionários receberá também o ano de contratação e o salário. Calcule e acrescente, além da idade, com quantos anos a pessoa vai se aposentar.</br>
(Considerar aposentadoria após 35 anos de contribuição.)

In [58]:
from datetime import datetime

dados = dict()
dados['nome'] = str(input('Nome: '))
nasc = int(input('Ano de Nascimento: '))
dados['idade'] = datetime.now().year - nasc
dados['ctps'] = int(input('Carteira de Trabalho (0 não tem): '))
if dados['ctps'] != 0:
    dados['contratação'] = int(input('Ano de Contratação> '))
    dados['salario'] = float(input('Salário: R$'))
    dados['aposentadoria'] = dados['idade'] + ((dados['contratação'] + 35) - datetime.now().year)
print('-=' * 30)
for k, v in dados.items():
    print(f'  - {k} tem o valor {v}')

Nome: João
Ano de Nascimento: 1995
Carteira de Trabalho (0 não tem): 3333
Ano de Contratação> 2000
Salário: R$1000
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  - nome tem o valor João
  - idade tem o valor 29
  - ctps tem o valor 3333
  - contratação tem o valor 2000
  - salario tem o valor 1000.0
  - aposentadoria tem o valor 40


##  <font color = 'red'> Desafio 093 - Cadastro de Jogador de Futebol</font>
Crie um programa que gerencie o aproveitamento de um jogador de futebol. O programa vai ler o nome do jogador e quantas partidas ele jogou.</br>
Depois vai ler a quantidade de gols feitos em cada partida. No final, tudo isso será guardado em um dicionário, incluindo o total de gols feitos durante o campeonato.

In [60]:
jogador = dict()
partidas = list()
jogador['nome'] = str(input('Nome do Jogador: '))
tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))
for c in range(0, tot):
    partidas.append(int(input(f'    Quantos gols na partida {c}?' )))
jogador['gols'] = partidas[:]
jogador['total'] = sum(partidas)
print('-=' * 30)
print(jogador)
print('-=' * 30)
for k, v in jogador.items():
    print(f'O campo {k} tem o valor {v}')
print('-=' * 30)
print(f'O jogador {jogador["nome"]} jogou {len(jogador["gols"])} partidas.')
for i, v in enumerate(jogador['gols']):
    print(f'    => Na partida {i+1}, fez {v} gols.')
print(f'Foi um total de {jogador["total"]} gols.')


Nome do Jogador: Hélio
Quantas partidas Hélio jogou? 3
    Quantos gols na partida 0?4
    Quantos gols na partida 1?0
    Quantos gols na partida 2?1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
{'nome': 'Hélio', 'gols': [4, 0, 1], 'total': 5}
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O campo nome tem o valor Hélio
O campo gols tem o valor [4, 0, 1]
O campo total tem o valor 5
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O jogador Hélio jogou 3 partidas.
    => Na partida 0, fez 4 gols.
    => Na partida 1, fez 0 gols.
    => Na partida 2, fez 1 gols.
Foi um total de 5 gols.


##  <font color = 'red'> Desafio 094 - Unindo dicionários e listas</font>
Crie um programa que leia nome, sexo e idade de várias pessoas, guardando os dados de cada pessoa em um dicionário e todos os dicionários em uma lista. No final, mostre:
- A) Quantas pessoas foram cadastradas.
- B) A média de idade do grupo.
- C) Uma lista com todas as mulheres.
- D) Uma lista com todas as pessoas com idade acima da média.

In [66]:
galera = list()
pessoa = dict()
soma = media = 0
while True:
    pessoa.clear()
    pessoa['nome'] = str(input("Nome: "))
    while True:
        pessoa['sexo'] = str(input('Sexo: [M/F] ')).upper()[0]
        if pessoa['sexo'] in 'MF':
            break
        print('ERRO! Por Favor, digite apenas M ou F.')
    pessoa['idade'] = int(input("Idade: "))
    soma += pessoa['idade']
    galera.append(pessoa.copy())
    while True:
        resp = str(input('Quer continuar? [S/N] ')).upper()[0]
        if resp in 'SN':
            break
        print('ERRO! Responda apenas S ou N.')
    if resp == 'N':
        break
    print('')
print('-=' * 30)
print(f'A) Ao todo temos {len(galera)} pessoas cadastradas')
media = soma / len(galera)
print(f'B) A média de idade é de {media:5.2f} anos.')
print(f'C) As mulheres cadastradas foram: ', end='')
for p in galera:
    if p['sexo'] in 'Ff':
        print(f'{p["nome"]} ', end='')
print()
print('D) Lista das pessoas que estao acima da média: ')
for p in galera:
    if p['idade'] >= media:
        print('    ')
        for k, v in p.items():
            print(f'{k} = {v}; ' end='')
        print()

Nome: Gustavo
Sexo: [M/F] m
Idade: 40
Quer continuar? [S/N] s

Nome: Maria
Sexo: [M/F] f
Idade: 22
Quer continuar? [S/N] s

Nome: Jéssica
Sexo: [M/F] f
Idade: 12
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A) Ao todo temos 3 pessoas cadastradas
B) A média de idade é de 24.67 anos.
C) As mulheres cadastradas foram Maria Jéssica 

##  <font color = 'red'> Desafio 095 - Aprimorando os Dicionários</font>
Aprimore o Desafio 093 para que ele funcione com vários jogadores, incluindo um sistema de visualização de detalhes do aproveitamento de cada jogador.</br>
(Use o 999 para parar o programa.)

In [13]:
time = list()
jogador = dict()
partidas = list()
while True:
    jogador.clear()
    jogador['nome'] = str(input('Nome do Jogador: '))
    tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))
    partidas.clear()
    for c in range(0, tot):
        partidas.append(int(input(f'    Quantos gols na partida {c+1}?' )))
    jogador['gols'] = partidas[:]
    jogador['total'] = sum(partidas)
    time.append(jogador.copy())
    while True:
        resp = str(input('Quer cotinuar? [S/N]')).upper()[0]
        if resp in 'SN':
            break
        print('ERRO! Responda apenas S ou N.')
    if resp == 'N':
        break
print('-=' * 30)
print('cod ', end='')
for i in jogador.keys():
    print(f'{i:<15}', end='')
print()
print('-' * 40)
for k, v in enumerate(time):
    print(f'{k:>3} ', end='')
    for d in v.values():
        print(f'{str(d):<15}', end='')
    print()
print('-' * 40)
while True:
    busca = int(input('Mostrar dados de qual jogador? (999 para parar) '))
    if busca == 999:
        break
    if busca >= len(time):
        print(f'Erro! Não existe jogador com código {busca}!')
    else:
        print(f' -- LEVANTAMENTO DO JOGADOR {time[busca]["nome"]}:')
        for i, g in enumerate(time[busca]['gols']):
            print(f'     No jogo {i+1} fez {g} gols.')
    print('-' * 40)
print('<< VOLTE SEMPRE >>')


Nome do Jogador: Pedro
Quantas partidas Pedro jogou? 3
    Quantos gols na partida 1?1
    Quantos gols na partida 2?2
    Quantos gols na partida 3?3
Quer cotinuar? [S/N]s
Nome do Jogador: Maria
Quantas partidas Maria jogou? 4
    Quantos gols na partida 1?5
    Quantos gols na partida 2?3
    Quantos gols na partida 3?4
    Quantos gols na partida 4?1
Quer cotinuar? [S/N]s
Nome do Jogador: Ronaldo
Quantas partidas Ronaldo jogou? 1
    Quantos gols na partida 1?7
Quer cotinuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
cod nome           gols           total          
----------------------------------------
  0 Pedro          [1, 2, 3]      6              
  1 Maria          [5, 3, 4, 1]   13             
  2 Ronaldo        [7]            7              
----------------------------------------
Mostrar dados de qual jogador? (999 para parar) 8
Erro! Não existe jogador com código 8!
----------------------------------------
Mostrar dados de qual jogador? (999 

##  <font color = 'red'> Desafio 096 - Função que calcula área</font>
Faça um programa que tenha uma função chamada área(), que receba as dimensões de um terreno retangular (largura e comprimento) e mostre a área do terreno.

In [14]:
def area(larg, comp):
    a = larg * comp
    print(f'A área de um terreno com {larg} x {comp} é de {a}m².')
    
print('Controle de Terrenos')
print('-' * 20)
l = float(input('LARGURA (m):' ))
c = float(input('COMPRIMENTO (m): '))
area(l, c)


Controle de Terrenos
--------------------
LARGURA (m):5
COMPRIMENTO (m): 4
A área de um terreno com 5.0x4.0 é de 20.0m².


##  <font color = 'red'> Desafio 097 - Um print especial</font>
Faça um programa que tenha uma função chamada escreva(), que receba um texto qualquer como parâmetro e mostre uma mensagem com tamanho adaptável.</br>
Ex: escreva('Olá, Mundo!')</br>
Saída:</br>
=-=-=-===-=-=-=-=-=</br>
Olá, Mundo!</br>
=-=-=-===-=-=-=-=-=

In [15]:
def escreva(msg):
    tam = len(msg) + 4
    print('~' * tam)
    print(f'  {msg}')
    print('~' * tam)

escreva('Gustavo Guanabara')
escreva('Curso de Python no YouTube')
escreva('CeV')


~~~~~~~~~~~~~~~~~~~~~
  Gustavo Guanabara
~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Curso de Python no YouTube
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~
  CeV
~~~~~~~


##  <font color = 'red'> Desafio 098- Função de Contador</font>
Faça um programa que tenha uma função chamda contador(), que receba três parâmetros: início, fim e passo e realize a contagem.</br>
Seu programa tem que realizar três contagens através da função criada:
- A) De 1 até 10, de 1 em 1.
- B) De 10 até 0, de 2 em 2.
- C) Uma contagem personalizada.

In [31]:
from time import sleep

def contador(i, f, p):
    if p < 0:
        p *= -1
    if p == 0:
        p = 1
        
    print('-=' * 20)
    print(f'Contagem de {i} até {f} de {p} em {p}.')
    
    if i < f:
        cont = i
        while cont <= f:
            print(f'{cont} ', end='', flush=True)
            sleep(0.5)
            cont += p
        print('FIM!')
    else:
        cont = i
        while cont >= f:
            print(f'{cont} ', end='', flush=True)
            sleep(0.5)
            cont -= p
        print('FIM!')
    
contador(1, 10, 1)
contador(10, 0, 2)
print('-=' * 20)
print('Agora é sua vez de personalizar a contagem!')
ini = int(input('Inicio:' ))
fim = int(input('Fim:' ))
pas = int(input('Passo:' ))
contador(ini, fim, pas)


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Contagem de 1 até 10 de 1 em 1.
1 2 3 4 5 6 7 8 9 10 FIM!
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Contagem de 10 até 0 de 2 em 2.
10 8 6 4 2 0 FIM!
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Agora é sua vez de personalizar a contagem!
Inicio:-10
Fim:10
Passo:-4
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Contagem de -10 até 10 de 4 em 4.
-10 -6 -2 2 6 10 FIM!


##  <font color = 'red'> Desafio 099 - Função que descobre o maior</font>
Faça um programa que tenha uma função chamda maior(), que receba vários parâmetros com valores inteiros.</br>

Seu programa tem que analisar todos os valores e dizer qual deles é maior.

In [40]:
from time import sleep

def maior(*num):
    cont = maior = 0
    print('-=' * 30)
    print('Analisando os valores passador...')
    for valor in num:
        print(f'{valor} ', end='', flush=True)
        sleep(0.3)
        if cont == 0:
            maior = valor
        else:
            if valor > maior:
                maior = valor
        cont += 1
    print(f'Foram informado {cont} valores ao todo.')
    print(f'O maior valor informado foi {maior}.')

maior(2, 9, 4, 5, 7, 1)
maior(4, 7, 0)
maior(1, 2)
maior(6)
maior()


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Analisando os valores passador...
2 9 4 5 7 1 Foram informado 6 valores ao todo.
O maior valor informado foi 9.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Analisando os valores passador...
4 7 0 Foram informado 3 valores ao todo.
O maior valor informado foi 7.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Analisando os valores passador...
1 2 Foram informado 2 valores ao todo.
O maior valor informado foi 2.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Analisando os valores passador...
6 Foram informado 1 valores ao todo.
O maior valor informado foi 6.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Analisando os valores passador...
Foram informado 0 valores ao todo.
O maior valor informado foi 0.


##  <font color = 'red'> Desafio 100 - Funções para sortear e somar</font>
Faça um programa que tenha uma lista chamda números e duas funções chamadas sorteia() e somaPar(). A primeira função vai sortear 5 números e vai colocá-los dentro da lista e a segunda função vai mostrar a soma entre todos os valores PARES sorteados pela função anterior.

In [47]:
from random import randint
from time import sleep

def sorteia(lista):
    print('Sorteando 5 valores da lista: ', end='')
    for cont in range(0, 5):
        n = randint(1, 10)
        lista.append(n)
        print(f'{n} ', end='', flush=True)
        sleep(0.3)
    print('PRONTO')
    
def somaPar(lista):
    soma = 0
    for valor in lista:
        if valor % 2 == 0:
            soma += valor
    print(f'Somando os valores pares de {lista}, temos {soma}.')
        
numeros = list()
sorteia(numeros)
somaPar(numeros)


Sorteando 5 valores da lista: 8 10 3 5 4 PRONTO
Somando os valores pares de [8, 10, 3, 5, 4], temos 22.


##  <font color = 'red'> Desafio 101 - Funções para votação</font>
Crie um programa que tenha uma função chamada voto() que vai receber como parâmetro o ano de nascimento de uma pessoa, retornando um valor literal indicando se uma pessoa tem voto NEGADO, OPCIONAL ou OBRIGATÓRIO nas eleições.

Aqui explorado a ideia de escopo de importação.

In [56]:
def voto(ano):
    from datetime import date
    atual = date.today().year
    idade = atual - ano
    if idade < 16:
        return f'Com {idade} anos: NÃO VOTA.'
    elif 16 <= idade < 18 or idade > 65:
        return f'Com {idade} anos: VOTO OPCIONAL.'
    else:
        return f'Com {idade} anos: VOTO OBRIGATÓRIO.'

nasc = int(input('Em que ano você nasceu? '))
print(voto(nasc))


Em que ano você nasceu? 1971
Com 53 anos: VOTO OBRIGATÓRIO.


##  <font color = 'red'> Desafio 102 - Função para Fatorial</font>
Crie um programa que tenha uma função fatorial() que receba dois parâmetros: o primeiro que indique o número a calcular e o outro chamado show, que será um valor lógico (opcional) indicando se será mostrado ou não na tela o processo cálculo do fatorial.

In [1]:
def fatorial(n, show=False):
    """
    -> Calcula o Fatorial de um número.
    :param n: O número a ser calculado.
    :param show: (opcional) Mostra ou não a conta.
    :return: O valor do Fatorial de um número n.
    """
    f = 1
    for c in range(n, 0, -1):
        if show:
            print(c, end='')
            if c > 1:
                print(' x ', end='')
            else:
                print(' = ', end='')
        f *= c
    return f


print(fatorial(5, True))
print(fatorial(5))
help(fatorial)

5 x 4 x 3 x 2 x 1 = 120
120
Help on function fatorial in module __main__:

fatorial(n, show=False)
    -> Calcula o Fatorial de um número.
    :param n: O número a ser calculado.
    :param show: (opcional) Mostra ou não a conta.
    :return: O valor do Fatorial de um número n.



##  <font color = 'red'> Desafio 103 - Ficha do Jogador</font>
Faça um programa que tenha uma função chamada ficha(), que receba dois parâmetros opcionais: o nome de um jogador e quantos gols ele marcou.</br>
O programa deverá ser  capaz de mostrar a ficha do jogador, mesmo que algum dado não tenha sido informado corretamente.

In [5]:
def ficha(jog='<desconhecido>', gol=0):
    print(f'O jogador {jog} fez {gol} gol(s) no campeonato.')

    
n = str(input('Nome do Jogador: '))
g = str(input('Número de Gols: '))
if g.isnumeric():
    g = int(g)
else:
    g = 0
if n.strip() == '':
    ficha(gol=g)
else:
    ficha(n, g)


Nome do Jogador: 0
Número de Gols: b
O jogador 0 fez 0 gol(s) no campeonato.


##  <font color = 'red'> Desafio 104 - Validando entrada de dados em Python</font>
Crie um programa que tenha a função leiaInt(), que vai funcionar de forma semelhante à função input() do Python, só que fazendo a validação para aceitar apenas um valor numérico.</br>
Ex: n = leiaInt('Digite um número: ")

In [8]:
def leiaInt(msg):
    ok = False
    valor = 0
    while True:
        n = str(input(msg))
        if n.isnumeric():
            valor = int(n)
            ok = True
        else:
            print('\033[0;31mErro! Digite um número inteiro válido.\033[m')
        if ok:
            break
    return valor


n = leiaInt('Digite um número: ')
print(f'Você acabou de digitar o número {n}.')

Digite um número: adfasd
Erro! Digite um número inteiro válido.
Digite um número: $
Erro! Digite um número inteiro válido.
Digite um número: 100
Você acabou de digitar o número 100.


##  <font color = 'red'> Desafio 105 - Analisando e gerando Dicionários</font>
Faça um programa que tenha uma função notas() que pode receber várias notas de alunos e vai retornar um dicionário com as seguintes informações:
- Quantidade de notas
- A maior nota
- A menor nota
- A média da turma
- A situação (opcional)

Adicione também as docstrings da função.

In [9]:
def notas(*n, sit=False):
    '''
    -> Função para analisar notas e situações de vários alunos.
    :param n: uma ou mais notas dos alunos (aceita várias notas).
    :param sit: valor opcional, indicando se deve ou não adicionar a situação.
    :return: dicionário com várias informações sobre a situação da turma.
    '''
    r = dict()
    r['total'] = len(n)
    r['maior'] = max(n)
    r['menor'] = min(n)
    r['media'] = sum(n) / len(n)
    if sit:
        if r['media'] >= 7:
            r['situacao'] = 'BOA'
        elif r['media'] >= 5:
            r['situacao'] = 'REZOÁVEL'
        else:
            r['situacao'] = 'RUIM'
    return r


resp = notas(5.5, 2.5, 1.5, sit=True)
print(resp)
help(notas)

{'total': 3, 'maior': 5.5, 'menor': 1.5, 'media': 3.1666666666666665, 'situacao': 'RUIM'}
Help on function notas in module __main__:

notas(*n, sit=False)
    -> Função para analisar notas e situações de vários alunos.
    :param n: uma ou mais notas dos alunos (aceita várias notas).
    :param sit: valor opcional, indicando se deve ou não adicionar a situação.
    :return: dicionário com várias informações sobre a situação da turma.



##  <font color = 'red'> Desafio 106 - Sistema interativo de ajuda em Python </font>
Faça um minisistema que utilize o Interactive Help do Python. O usuário vai digitar o comando e o manual para aparecer. Quando o usuário digitar a palavra 'FIM', o programa se encerrará. Obs: use cores.

In [23]:
from time import sleep

c = ('\033[m',         # 0 - sem cores
     '\033[0;30;41m',   # 1 - vermelho
     '\033[0;30;42m',   # 2 - verde
     '\033[0;30;43m',   # 3 - amarelo
     '\033[0;30;44m',   # 4 - azul
     '\033[0;30;45m',   # 5 - roxo
     '\033[7;30m'       # 6 - branco
    )

def ajuda(com):
    titulo(f'Acessando o manual do comando \'{com}\'',4)
    print(c[0], end='')
    help(com)
    print(c[0], end='')
    sleep(2)
    

def titulo(msg, cor=0):
    tam = len(msg) + 4
    print(c[cor], end='')
    print('~' * tam)
    print(f'  {msg}')
    print('~' * tam)
    print(c[cor], end='')
    sleep(1)
        

comando = ''
while True:
    titulo('SISTEMA DE AJUDA PyHELP', 2)
    print(c[0], end='')
    comando = str(input('Função ou Biblioteca > '))
    if comando.upper() == 'FIM':
        break
    else:
        ajuda(comando)
titulo('ATÉ LOGO', 1)


~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SISTEMA DE AJUDA PyHELP
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Função ou Biblioteca > len
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Acessando o manual do comando 'len'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SISTEMA DE AJUDA PyHELP
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Função ou Biblioteca > fim
~~~~~~~~~~~~
  ATÉ LOGO
~~~~~~~~~~~~


##  <font color = 'red'> Desafio 107 - Exercitando módulos em Python</font>
Crie um módulo chamado moeda.py que tenha as punções incporporadas aumentar(), diminuir( ), dobra( ) e metade( ).</br>

Faça também um programa que importe esse módulo e use algumas dessas funções.

In [62]:
from ex_107 import moeda

p = float(input('Digite um preço: R$ '))
print(f'A metade do R${p} é R${moeda.metade(p)}')
print(f'O dobro de R${p} é R${moeda.dobro(p)}')
print(f'Aumentando 10%, temos R${moeda.aumentar(p, 10)}')

Digite um preço: R$ 200
A metade do R$200.0 é R$100.0
O dobro de R$200.0 é R$400.0
Aumentando 10%, temos R$220.0


##  <font color = 'red'> Desafio 108 - Formatando Moedas em Python</font>
Adapte o código do desafio 107, criando uma função adicional chamada moeda( ) que consiga mostrar os valoes com um valor monterário formatado.

In [63]:
from ex_108 import moeda

p = float(input('Digite um preço: R$ '))
print(f'A metade do {moeda.moeda(p)} é {moeda.moeda(moeda.metade(p))}')
print(f'O dobro de {moeda.moeda(p)} é {moeda.moeda(moeda.dobro(p))}')
print(f'Aumentando 10%, temos {moeda.moeda(moeda.aumentar(p, 10))}')

Digite um preço: R$ 200
A metade do R$  200,00 é R$  100,00
O dobro de R$  200,00 é R$  400,00
Aumentando 10%, temos R$  220,00


##  <font color = 'red'> Desafio 109 - Formatando Moedas em Python</font>
Modifique as funções que foram criadas no Desafio 107 para que elas aceitem um parâmetro a mais, informando se o valor retornado por elas vai ser ou não formadado pela função modeda( ), desenvolvida no Desafio 108.

In [19]:
from ex_109 import moeda

p = float(input('Digite um preço: R$ '))
print(f'A metade do {moeda.moeda(p)} é {moeda.metade(p, True)}')
print(f'O dobro de {moeda.moeda(p)} é {moeda.dobro(p)}')
print(f'Aumentando 10%, temos {moeda.aumentar(p, 10)}')
print(f'Reduzindo 13%, temos {moeda.diminuir(p, 13)}')

Digite um preço: R$ 123
A metade do R$123,00 é R$61,50
O dobro de R$123,00 é 246.0
Aumentando 10%, temos 135.3
Reduzindo 13%, temos 107.01


##  <font color = 'red'> Desafio 110 - Reduzinda ainda mais seu programa</font>
Adicione ao módulo moeda.py criado nos desafios anteriores, uma função chamada resumo( ), que mostre na tela algumas informações geradas pelas funções que já temos no módulo criado até aqui.

In [36]:
from ex_110 import moeda

p = float(input('Digite um preço: R$ '))
moeda.resumo(p)

Digite um preço: R$ 123
------------------------------
       RESUMO DO VALOR        
------------------------------
Preço analisado: 	R$123,00
Dobro do preço: 	(246.0, True)
Metade do preço: 	(61.5, True)
10% de aumento: 	(135.3, True)
5% de redução: 	(116.85, True)
------------------------------


##  <font color = 'red'> Desafio 111 - Transformando módulos em pacotes</font>
Crie um pacote chamado utilidadesCeV que tenha dois módulos internos chamados moeda e dado.</br>

Transfira todas as funções utilizadas no desafios 107, 108 e 109 para o primeiro pacote e mantenha tudo funcionando.

In [51]:
from ex111.utilizadadeCeV import moeda, dado

p = float(input('Digite um preço: R$ '))
moeda.resumo(p, 20, 15)

Digite um preço: R$ 123
------------------------------
       RESUMO DO VALOR        
------------------------------
Preço analisado: 	R$123,00
Dobro do preço: 	R$246,00
Metade do preço: 	R$61,50
20% de aumento: 	R$147,60
15% de redução: 	R$104,55
------------------------------


##  <font color = 'red'> Desafio 112 - Entrada de dados monetários</font>
Dentro do pacote utilidadesCeV que criamos no Desafio 111, temos um módulo chamado dado. Crie uma função chamada leiaDinheiro( ) que seja capaz de funcionar como a função input( ), mas com a validação de dados para aceitar apenas valores que sejam monteráios.

In [50]:
from ex112.utilizadadeCeV import moeda, dado

p = dado.leiaDinheiro('Digite um preço: R$ ')
moeda.resumo(p, 35, 22)

Digite um preço: R$ 123
------------------------------
       RESUMO DO VALOR        
------------------------------
Preço analisado: 	R$123,00
Dobro do preço: 	R$246,00
Metade do preço: 	R$61,50
35% de aumento: 	R$166,05
22% de redução: 	R$95,94
------------------------------


##  <font color = 'red'> Desafio 113 - Função aprofundadas em Python</font>
Reescreva a função leiaInt que fizemos no desafio 104, incluindo agora a possibilidade da digitação de um número de tipo inválido. Aproveite e crie também uma função leiaFloat( ) com a mesma funcionalidade.

In [67]:
def leiaInt(msg):
    while True:
        try:
            n = int(input(msg))
        except (ValueError, TypeError):
            print('\033[31mERRO: por favor, digite um número inteiro válido.\033[m')
            continue
        except (KeyboardInterrupt):
            print('\n\033[31mUsuário preferiu não digitar esse número.\033[m')
            return 0
        else:
            return n
        

def leiaFloat(msg):
    while True:
        try:
            n = float(input(msg))
        except (ValueError, TypeError):
            print('\033[31mERRO: por favor, digite um número real válido.\033[m')
            continue
        except (KeyboardInterrupt):
            print('\n\033[31mUsuário preferiu não digitar esse número.\033[m')
            return 0
        else:
            return n
        

n1 = leiaInt('Digite um número Inteiro: ')
n2 = leiaFloat('Digite um número Real: ')
print(f'O valor inteiro digitado foi {n1} e o real foi {n2}')


Digite um número Inteiro: 9
Digite um número Real: 9
O valor inteiro digitado foi 9 e o real foi 9.0


##  <font color = 'red'> Desafio 114 - Site está acessível</font>
Crie um código em Python que teste se o site Pudim está acessível pelo computador usado.
(NÃO CONSEGUI RODAR ESSE EXERCÍCIO)

In [101]:
# import urllib
import urllib.request

try:
    site = urllib.request.urlopen('http://www.pudim.com.br/')
except urllib.error.URLError:
    print('O site Pudim não está acessível no momento.')
else:
    print('Consegui acessar o site Pudim com sucesso.')

O site Pudim não está acessível no momento.


##  <font color = 'red'> Desafio 115 - Criando um menu em Python 1/3</font>
Crie um pequeno sistema modularizado que permita cadastrar pessoas pelo seu nome e idade em um arquivo de texto simples.</br>

O sistema só vai ter 2 opções: cadastrar uma nova pessoa e listar todas as pessoas cadastradoas.

In [112]:
from ex115.lib.interface import *
from time import sleep

while True:
    resposta = menu(['Ver pessoas cadastradas',
                    'Cadastrar nova Pessoa', 'Sair do Sistema'])
    if resposta == 1:
        cabeçalho('Opção 1')
    elif resposta == 2:
        cabeçalho('Opção 2')
    elif resposta == 3:
        cabeçalho('Saindo do sistema... até logo!')
        break
    else:
        print('\033[31mERRO: digite uma opção válida.\033[m')
    sleep(2)

------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 1
------------------------------------------
                 Opção 1                  
------------------------------------------
------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 2
------------------------------------------
                 Opção 2                  
------------------------------------------
------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
---------------------

##  <font color = 'red'> Desafio 115 - Criando um menu em Python 2/3</font>

In [113]:
from ex115.lib.interface import *
from ex115.lib.arquivo import *
from time import sleep

arq = 'cursoemvideo.txt'

if not arquivoExiste(arq):
    criarArquivo(arq)

while True:
    resposta = menu(['Ver pessoas cadastradas',
                    'Cadastrar nova Pessoa', 'Sair do Sistema'])
    if resposta == 1:
        # Opção de listar o condeúdo de um arquivo.
        lerArquivo(arq)
    elif resposta == 2:
        cabeçalho('Opção 2')
    elif resposta == 3:
        cabeçalho('Saindo do sistema... até logo!')
        break
    else:
        print('\033[31mERRO: digite uma opção válida.\033[m')
    sleep(2)


------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 1
------------------------------------------
           PESSOAS CADASTRADAS            
------------------------------------------
Gustavo;41
Ana;22
Pedro;35
Paulo;95
JosÃ©;55
------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 3
------------------------------------------
      Saindo do sistema... até logo!      
------------------------------------------


##  <font color = 'red'> Desafio 115 - Criando um menu em Python 3/3</font>

In [114]:
from ex115.lib.interface import *
from ex115.lib.arquivo import *
from time import sleep

arq = 'cursoemvideo.txt'

if not arquivoExiste(arq):
    criarArquivo(arq)

while True:
    resposta = menu(['Ver pessoas cadastradas',
                    'Cadastrar nova Pessoa', 'Sair do Sistema'])
    if resposta == 1:
        # Opção de listar o condeúdo de um arquivo.
        lerArquivo(arq)
    elif resposta == 2:
        # Opção de cadastrar uma nova pessoa.
        cabeçalho('NOVO CADASTRO')
        nome = str(input('Nome: '))
        idade = leiaInt('Idade: ')
        cadastrar(arq, nome, idade)
    elif resposta == 3:
        cabeçalho('Saindo do sistema... até logo!')
        break
    else:
        print('\033[31mERRO: digite uma opção válida.\033[m')
    sleep(2)


------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 1
------------------------------------------
           PESSOAS CADASTRADAS            
------------------------------------------
José;35
Gustavo;41
Maria;85

------------------------------------------
              MENU PRINCIPAL              
------------------------------------------
1 - Ver pessoas cadastradas
2 - Cadastrar nova Pessoa
3 - Sair do Sistema
------------------------------------------
Sua Opção: 3
------------------------------------------
      Saindo do sistema... até logo!      
------------------------------------------
